# 00. PyTorch Fundamentals

## What is PyTorch?

[PyTorch](https://pytorch.org/) is an open source machine learning and deep learning framework.

## What can PyTorch be used for?

PyTorch allows you to manipulate and process data and write machine learning algorithms using Python code.

## Who uses PyTorch?

Many of the worlds largest technology companies such as [Meta (Facebook)](https://ai.facebook.com/blog/pytorch-builds-the-future-of-ai-and-machine-learning-at-facebook/), Tesla and Microsoft as well as artificial intelligence research companies such as [OpenAI use PyTorch](https://openai.com/blog/openai-pytorch/) to power research and bring machine learning to their products.

![pytorch being used across industry and research](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-being-used-across-research-and-industry.png)

For example, Andrej Karpathy (head of AI at Tesla) has given several talks ([PyTorch DevCon 2019](https://youtu.be/oBklltKXtDE), [Tesla AI Day 2021](https://youtu.be/j0z4FweCy4M?t=2904)) about how Tesla use PyTorch to power their self-driving computer vision models.

PyTorch is also used in other industries such as agriculture to [power computer vision on tractors](https://medium.com/pytorch/ai-for-ag-production-machine-learning-for-agriculture-e8cfdb9849a1).

## Why use PyTorch?

Machine learning researchers love using PyTorch. And as of February 2022, PyTorch is the [most used deep learning framework on Papers With Code](https://paperswithcode.com/trends), a website for tracking machine learning research papers and the code repositories attached with them.

PyTorch also helps take care of many things such as GPU acceleration (making your code run faster) behind the scenes.

So you can focus on manipulating data and writing algorithms and PyTorch will make sure it runs fast.

And if companies such as Tesla and Meta (Facebook) use it to build models they deploy to power hundreds of applications, drive thousands of cars and deliver content to billions of people, it's clearly capable on the development front too.

## What we're going to cover in this module

This course is broken down into different sections (notebooks).

Each notebook covers important ideas and concepts within PyTorch.

Subsequent notebooks build upon knowledge from the previous one (numbering starts at 00, 01, 02 and goes to whatever it ends up going to).

This notebook deals with the basic building block of machine learning and deep learning, the tensor.

Specifically, we're going to cover:

| **Topic** | **Contents** |
| ----- | ----- |
| **Introduction to tensors** | Tensors are the basic building block of all of machine learning and deep learning. |
| **Creating tensors** | Tensors can represent almost any kind of data (images, words, tables of numbers). |
| **Getting information from tensors** | If you can put information into a tensor, you'll want to get it out too. |
| **Manipulating tensors** | Machine learning algorithms (like neural networks) involve manipulating tensors in many different ways such as adding, multiplying, combining. |
| **Dealing with tensor shapes** | One of the most common issues in machine learning is dealing with shape mismatches (trying to mixed wrong shaped tensors with other tensors). |
| **Indexing on tensors** | If you've indexed on a Python list or NumPy array, it's very similar with tensors, except they can have far more dimensions. |
| **Mixing PyTorch tensors and NumPy** | PyTorch plays with tensors ([`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html)), NumPy likes arrays ([`np.ndarray`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)) sometimes you'll want to mix and match these. |
| **Reproducibility** | Machine learning is very experimental and since it uses a lot of *randomness* to work, sometimes you'll want that *randomness* to not be so random. |
| **Running tensors on GPU** | GPUs (Graphics Processing Units) make your code faster, PyTorch makes it easy to run your code on GPUs. |

## Where can you get help?

All of the materials for this course [live on GitHub](https://github.com/mrdbourke/pytorch-deep-learning).

And if you run into trouble, you can ask a question on the [Discussions page](https://github.com/mrdbourke/pytorch-deep-learning/discussions) there too.

There's also the [PyTorch developer forums](https://discuss.pytorch.org/), a very helpful place for all things PyTorch.

## Importing PyTorch

> **Note:** Before running any of the code in this notebook, you should have gone through the [PyTorch setup steps](https://pytorch.org/get-started/locally/).
>
> However, **if you're running on Google Colab**, everything should work (Google Colab comes with PyTorch and other libraries installed).

Let's start by importing PyTorch and checking the version we're using.

In [1]:
import torch
torch.__version__

'2.1.0+cu121'

Kode di atas menggunakan modul PyTorch untuk mencetak versi PyTorch yang sedang digunakan. Berikut adalah penjelasan singkat:

import torch: Ini mengimpor modul PyTorch ke dalam skrip atau lingkungan kerja Python Anda.

torch.__version__: Ini adalah properti yang memberikan versi PyTorch yang sedang digunakan. Dengan menjalankan torch.__version__, Anda dapat melihat versi PyTorch yang terpasang pada sistem Anda.

Anda dapat mengeksekusi kode ini untuk mendapatkan versi PyTorch yang sedang Anda gunakan dalam lingkungan Python Anda saat ini. Misalnya, hasilnya bisa seperti "1.8.1" atau versi lainnya, tergantung pada versi PyTorch yang Anda miliki diinstal.

Wonderful, it looks like we've got PyTorch 1.10.0+.

This means if you're going through these materials, you'll see most compatability with PyTorch 1.10.0+, however if your version number is far higher than that, you might notice some inconsistencies.

And if you do have any issues, please post on the course [GitHub Discussions page](https://github.com/mrdbourke/pytorch-deep-learning/discussions).

## Introduction to tensors

Now we've got PyTorch imported, it's time to learn about tensors.

Tensors are the fundamental building block of machine learning.

Their job is to represent data in a numerical way.

For example, you could represent an image as a tensor with shape `[3, 224, 224]` which would mean `[colour_channels, height, width]`, as in the image has `3` colour channels (red, green, blue), a height of `224` pixels and a width of `224` pixels.

![example of going from an input image to a tensor representation of the image, image gets broken down into 3 colour channels as well as numbers to represent the height and width](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-tensor-shape-example-of-image.png)

In tensor-speak (the language used to describe tensors), the tensor would have three dimensions, one for `colour_channels`, `height` and `width`.

But we're getting ahead of ourselves.

Let's learn more about tensors by coding them.


### Creating tensors

PyTorch loves tensors. So much so there's a whole documentation page dedicated to the [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html) class.

Your first piece of homework is to [read through the documentation on `torch.Tensor`](https://pytorch.org/docs/stable/tensors.html) for 10-minutes. But you can get to that later.

Let's code.

The first thing we're going to create is a **scalar**.

A scalar is a single number and in tensor-speak it's a zero dimension tensor.

> **Note:** That's a trend for this course. We'll focus on writing specific code. But often I'll set exercises which involve reading and getting familiar with the PyTorch documentation. Because after all, once you're finished this course, you'll no doubt want to learn more. And the documentation is somewhere you'll be finding yourself quite often.

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

Kode di atas membuat sebuah tensor skalar menggunakan PyTorch. Berikut adalah penjelasan singkat:

torch.tensor(7): Membuat tensor skalar dengan nilai 7. Sebuah tensor skalar adalah tensor dengan hanya satu elemen atau nilai tunggal. Dalam konteks ini, tensor ini hanya berisi angka 7.

scalar: Variabel yang menampung tensor skalar tersebut.

scalar: Baris terakhir dari kode tersebut adalah untuk mencetak atau menampilkan nilai tensor skalar. Jika Anda mengeksekusi kode ini, Anda akan melihat keluaran yang berisi nilai skalar yang ditentukan, yaitu 7.

Jadi, secara keseluruhan, kode ini mengilustrasikan cara membuat tensor skalar menggunakan PyTorch dan menyimpannya dalam variabel scalar.

See how the above printed out `tensor(7)`?

That means although `scalar` is a single number, it's of type `torch.Tensor`.

We can check the dimensions of a tensor using the `ndim` attribute.

In [3]:
scalar.ndim

0

Dalam PyTorch, tensor skalar (tensor dengan hanya satu elemen) merupakan tensor 0 dimensi (dimensi nol). Kode scalar.ndim mencoba mengakses atribut ndim dari tensor scalar untuk mendapatkan jumlah dimensi tensor tersebut.

Namun, tensor skalar dalam PyTorch tidak memiliki atribut ndim karena dimensinya adalah 0. Sebagai gantinya, kita dapat menggunakan metode dim() untuk mendapatkan jumlah dimensi dari tensor

Dengan menggunakan dim(), kita dapat mengetahui bahwa tensor skalar memiliki 0 dimensi. Jadi, jika Anda menjalankan scalar.ndim, itu akan menghasilkan kesalahan karena atribut ndim tidak ditemukan pada tensor skalar dalam PyTorch.

What if we wanted to retrieve the number from the tensor?

As in, turn it from `torch.Tensor` to a Python integer?

To do we can use the `item()` method.

In [4]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

Kode di atas menggunakan metode .item() pada tensor skalar untuk mendapatkan nilai Python yang terkandung di dalam tensor tersebut. Berikut adalah penjelasan singkat:

scalar: Ini adalah tensor skalar yang telah dibuat sebelumnya. Dalam contoh ini, diasumsikan bahwa scalar adalah tensor skalar yang berisi satu elemen.

.item(): Metode ini digunakan untuk mengambil nilai Python dari tensor skalar. Dikarenakan tensor skalar hanya berisi satu elemen, metode ini dapat digunakan untuk mendapatkan nilai tersebut sebagai nilai Python biasa (int, float, dll.).

Dalam hal ini, python_number akan berisi nilai Python 7, karena tensor skalar hanya memiliki satu elemen dan .item() digunakan untuk mengakses nilai tersebut dalam bentuk Python. Penting untuk dicatat bahwa .item() hanya berlaku untuk tensor dengan satu elemen. Jika tensor memiliki lebih dari satu elemen, penggunaan .item() akan menghasilkan kesalahan.

Okay, now let's see a **vector**.

A vector is a single dimension tensor but can contain many numbers.

As in, you could have a vector `[3, 2]` to describe `[bedrooms, bathrooms]` in your house. Or you could have `[3, 2, 2]` to describe `[bedrooms, bathrooms, car_parks]` in your house.

The important trend here is that a vector is flexible in what it can represent (the same with tensors).

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

Kode di atas membuat sebuah tensor vektor menggunakan PyTorch. Berikut adalah penjelasan singkat:

torch.tensor([7, 7]): Membuat tensor vektor dengan dua elemen, yaitu 7 dan 7. Sebuah tensor vektor adalah tensor satu dimensi yang berisi sejumlah elemen.

vector: Variabel yang menampung tensor vektor tersebut.

vector: Baris terakhir dari kode tersebut adalah untuk mencetak atau menampilkan nilai tensor vektor. Jika Anda mengeksekusi kode ini, Anda akan melihat keluaran yang berisi nilai vektor yang ditentukan, yaitu [7, 7].

Jadi, secara keseluruhan, kode ini mengilustrasikan cara membuat tensor vektor dengan dua elemen menggunakan PyTorch dan menyimpannya dalam variabel vector.

Wonderful, `vector` now contains two 7's, my favourite number.

How many dimensions do you think it'll have?

In [6]:
# Check the number of dimensions of vector
vector.ndim

1

Dalam PyTorch, tensor vektor (tensor satu dimensi) memiliki satu dimensi. Kode vector.ndim mencoba untuk mengakses atribut ndim dari tensor vector untuk mendapatkan jumlah dimensi tensor tersebut.

Namun, tensor vektor dalam PyTorch sebenarnya tidak memiliki atribut ndim, karena dimensinya sudah terdefinisi sebagai satu dimensi. Sebagai gantinya, kita dapat menggunakan metode dim() untuk mendapatkan jumlah dimensi dari tensor.

Dengan menggunakan dim(), kita dapat mengetahui bahwa tensor vektor memiliki satu dimensi. Jadi, jika Anda menjalankan vector.ndim, itu mungkin menghasilkan kesalahan karena atribut ndim tidak ditemukan pada tensor vektor dalam PyTorch. Sebaiknya, gunakan metode dim() untuk mendapatkan jumlah dimensi.

Hmm, that's strange, `vector` contains two numbers but only has a single dimension.

I'll let you in on a trick.

You can tell the number of dimensions a tensor in PyTorch has by the number of square brackets on the outside (`[`) and you only need to count one side.

How many square brackets does `vector` have?

Another important concept for tensors is their `shape` attribute. The shape tells you how the elements inside them are arranged.

Let's check out the shape of `vector`.

In [7]:
# Check shape of vector
vector.shape

torch.Size([2])

Untuk mendapatkan bentuk (shape) dari tensor dalam PyTorch, Anda dapat menggunakan atribut shape. Namun, perlu diingat bahwa untuk tensor satu dimensi seperti vektor, hasilnya akan disajikan dalam bentuk tupel dengan satu elemen.

Output yang diharapkan dari kode ini adalah (2,). Ini menunjukkan bahwa vektor memiliki dua elemen dan merupakan tensor satu dimensi. Jadi, bentuknya adalah tupel dengan satu elemen yang menyatakan panjang vektor.

The above returns `torch.Size([2])` which means our vector has a shape of `[2]`. This is because of the two elements we placed inside the square brackets (`[7, 7]`).

Let's now see a **matrix**.

In [8]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

Kode di atas membuat sebuah tensor matriks menggunakan PyTorch. Berikut adalah penjelasan singkat:

torch.tensor([[7, 8], [9, 10]]): Membuat tensor matriks dengan dua baris dan dua kolom. Sebuah tensor matriks adalah tensor dua dimensi yang berisi elemen-elemen ini.

MATRIX: Variabel yang menampung tensor matriks tersebut.

MATRIX: Baris terakhir dari kode tersebut adalah untuk mencetak atau menampilkan nilai tensor matriks. Jika Anda mengeksekusi kode ini, Anda akan melihat keluaran yang berisi nilai matriks yang ditentukan.

Jadi, secara keseluruhan, kode ini mengilustrasikan cara membuat tensor matriks dengan elemen-elemen tertentu menggunakan PyTorch dan menyimpannya dalam variabel MATRIX.

Wow! More numbers! Matrices are as flexible as vectors, except they've got an extra dimension.



In [9]:
# Check number of dimensions
MATRIX.ndim

2

Untuk mendapatkan jumlah dimensi dari tensor dalam PyTorch, Anda dapat menggunakan metode dim() atau properti ndim. Namun, perlu diingat bahwa matriks adalah tensor dua dimensi.

Hasil dari MATRIX.dim() adalah 2, yang menunjukkan bahwa matriks memiliki dua dimensi. Jika Anda ingin menggunakan ndim, Anda dapat menggantinya dengan MATRIX.ndim, dan itu juga akan menghasilkan 2.

`MATRIX` has two dimensions (did you count the number of square brakcets on the outside of one side?).

What `shape` do you think it will have?

In [10]:
MATRIX.shape

torch.Size([2, 2])

Kode MATRIX.shape bertujuan untuk menampilkan bentuk (shape) dari suatu tensor matriks yang disimpan dalam variabel MATRIX. Berikut adalah penjelasan singkat:

MATRIX: Ini adalah variabel yang mengacu pada suatu tensor matriks PyTorch yang sudah didefinisikan sebelumnya.

.shape: Atribut ini digunakan untuk mendapatkan bentuk (shape) dari tensor. Bentuk tensor mencakup informasi tentang jumlah dimensi dan ukuran masing-masing dimensi.

MATRIX.shape: Eksekusi perintah ini akan mengembalikan bentuk tensor yang diakses melalui atribut shape. Outputnya berupa tupel yang menyatakan jumlah elemen dalam setiap dimensi.

Contoh output bisa berupa (2, 2), yang berarti matriks tersebut memiliki dua dimensi dengan dua elemen dalam setiap dimensinya. Pastikan bahwa variabel MATRIX telah didefinisikan sebagai tensor matriks PyTorch sebelumnya untuk menjalankan kode ini.

We get the output `torch.Size([2, 2])` because `MATRIX` is two elements deep and two elements wide.

How about we create a **tensor**?

In [11]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

Kode di atas menciptakan sebuah tensor tiga dimensi menggunakan PyTorch dan kemudian menampilkan nilai tensor tersebut. Berikut adalah penjelasan singkat:

torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]]): Membuat tensor tiga dimensi dengan nilai yang diberikan. Dalam hal ini, tensor tersebut memiliki tiga dimensi: satu dimensi untuk "tumpukan" lapisan, satu dimensi untuk baris, dan satu dimensi untuk kolom.

TENSOR: Variabel yang menampung tensor tiga dimensi yang baru dibuat.

TENSOR: Baris terakhir dari kode tersebut adalah untuk mencetak atau menampilkan nilai tensor tersebut. Jika Anda mengeksekusi kode ini, Anda akan melihat keluaran yang berisi nilai tensor tiga dimensi yang ditentukan.
Ini menunjukkan bahwa tensor tersebut memiliki tiga dimensi, dengan ukuran masing-masing dimensinya adalah 1, 3, dan 3. Pastikan bahwa variabel TENSOR telah didefinisikan sebagai tensor PyTorch sebelumnya untuk menjalankan kode ini.

Woah! What a nice looking tensor.

I want to stress that tensors can represent almost anything.

The one we just created could be the sales numbers for a steak and almond butter store (two of my favourite foods).

![a simple tensor in google sheets showing day of week, steak sales and almond butter sales](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00_simple_tensor.png)

How many dimensions do you think it has? (hint: use the square bracket counting trick)

In [12]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

Kode TENSOR.ndim mencoba untuk mengecek jumlah dimensi dari tensor yang disimpan dalam variabel TENSOR menggunakan properti ndim. Namun, perlu dicatat bahwa properti ndim tidak langsung tersedia pada objek tensor di PyTorch.

Dalam PyTorch, untuk mendapatkan jumlah dimensi dari suatu tensor, Anda dapat menggunakan metode dim() atau properti ndim.

Hasil dari TENSOR.dim() adalah 3, yang menunjukkan bahwa tensor tersebut memiliki tiga dimensi. Properti ndim tidak umum digunakan dalam konteks PyTorch, jadi sebaiknya menggunakan metode dim() untuk memeriksa jumlah dimensi dari suatu tensor.

And what about its shape?

In [13]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

Kode di atas bertujuan untuk menampilkan bentuk (shape) dari suatu tensor yang disimpan dalam variabel TENSOR menggunakan atribut shape. Berikut adalah penjelasan singkat:

TENSOR: Ini adalah variabel yang mengacu pada suatu tensor PyTorch yang sudah didefinisikan sebelumnya.

.shape: Atribut ini digunakan untuk mendapatkan bentuk (shape) dari tensor. Bentuk tensor mencakup informasi tentang jumlah dimensi dan ukuran masing-masing dimensi.

TENSOR.shape: Eksekusi perintah ini akan mengembalikan bentuk tensor yang diakses melalui atribut shape. Outputnya berupa tupel yang menyatakan jumlah elemen dalam setiap dimensi.

Contoh output bisa berupa (2, 3), yang berarti tensor tersebut memiliki dua dimensi dengan dua elemen dalam dimensi pertama dan tiga elemen dalam dimensi kedua. Pastikan bahwa variabel TENSOR telah didefinisikan sebagai tensor PyTorch sebelumnya untuk menjalankan kode ini.

Alright, it outputs `torch.Size([1, 3, 3])`.

The dimensions go outer to inner.

That means there's 1 dimension of 3 by 3.

![example of different tensor dimensions](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

> **Note:** You might've noticed me using lowercase letters for `scalar` and `vector` and uppercase letters for `MATRIX` and `TENSOR`. This was on purpose. In practice, you'll often see scalars and vectors denoted as lowercase letters such as `y` or `a`. And matrices and tensors denoted as uppercase letters such as `X` or `W`.
>
> You also might notice the names martrix and tensor used interchangably. This is common. Since in PyTorch you're often dealing with `torch.Tensor`s (hence the tensor name), however, the shape and dimensions of what's inside will dictate what it actually is.

Let's summarise.

| Name | What is it? | Number of dimensions | Lower or upper (usually/example) |
| ----- | ----- | ----- | ----- |
| **scalar** | a single number | 0 | Lower (`a`) |
| **vector** | a number with direction (e.g. wind speed with direction) but can also have many other numbers | 1 | Lower (`y`) |
| **matrix** | a 2-dimensional array of numbers | 2 | Upper (`Q`) |
| **tensor** | an n-dimensional array of numbers | can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector | Upper (`X`) |

![scalar vector matrix tensor and what they look like](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

### Random tensors

We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've being doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...`

As a data scientist, you can define how the machine learning model starts (initialization), looks at data (representation) and updates (optimization) its random numbers.

We'll get hands on with these steps later on.

For now, let's see how to create a tensor of random numbers.

We can do so using [`torch.rand()`](https://pytorch.org/docs/stable/generated/torch.rand.html) and passing in the `size` parameter.

In [14]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.7536, 0.2423, 0.4965, 0.7845],
         [0.1123, 0.5882, 0.4545, 0.8213],
         [0.0595, 0.7554, 0.7247, 0.9639]]),
 torch.float32)


Kode di atas menciptakan sebuah tensor acak dengan ukuran (3, 4) menggunakan PyTorch. Berikut adalah penjelasan singkat:

torch.rand(size=(3, 4)): Membuat tensor acak dengan ukuran (3, 4). Fungsi torch.rand() menghasilkan tensor dengan nilai acak yang terdistribusi seragam antara 0 dan 1. Parameter size digunakan untuk menentukan ukuran tensor yang diinginkan.

random_tensor: Variabel yang menampung tensor acak yang baru dibuat.

random_tensor.dtype: Mengakses properti dtype dari tensor untuk mendapatkan tipe data (dtype) tensor tersebut. Properti ini memberikan informasi tentang tipe data elemen dalam tensor.

Baris terakhir dari kode tersebut adalah untuk mencetak atau menampilkan nilai tensor acak dan tipe datanya. Jika Anda mengeksekusi kode ini, Anda akan melihat keluaran yang berisi nilai-nilai acak dan tipe data tensor tersebut.

Ini menunjukkan tensor acak dengan ukuran (3, 4) dan tipe data elemen float32. Pastikan bahwa variabel random_tensor telah didefinisikan sebelumnya untuk menjalankan kode ini.

The flexibility of `torch.rand()` is that we can adjust the `size` to be whatever we want.

For example, say you wanted a random tensor in the common image shape of `[224, 224, 3]` (`[height, width, color_channels`]).

In [15]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Kode di atas menciptakan sebuah tensor acak dengan ukuran (224, 224, 3) menggunakan PyTorch. Namun, perlu dicatat bahwa hal ini dapat menyebabkan masalah karena ukuran ini tidak sesuai dengan konvensi untuk representasi gambar dalam bentuk tensor.

Berikut adalah penjelasan singkat:

torch.rand(size=(224, 224, 3)): Membuat tensor acak dengan ukuran (224, 224, 3). Fungsi torch.rand() menghasilkan tensor dengan nilai acak yang terdistribusi seragam antara 0 dan 1. Parameter size digunakan untuk menentukan ukuran tensor yang diinginkan.

random_image_size_tensor: Variabel yang menampung tensor acak yang baru dibuat.

random_image_size_tensor.shape: Mengakses atribut shape dari tensor untuk mendapatkan bentuk (shape) tensor tersebut. Bentuk tensor memberikan informasi tentang jumlah dimensi dan ukuran masing-masing dimensi.

random_image_size_tensor.ndim: Mengakses metode ndim dari tensor untuk mendapatkan jumlah dimensi tensor tersebut.
Baris terakhir dari kode tersebut adalah untuk mencetak atau menampilkan bentuk dan jumlah dimensi tensor. Jika Anda mengeksekusi kode ini, Anda akan melihat keluaran yang berisi bentuk dan jumlah dimensi tensor tersebut.

Perlu dicatat bahwa ukuran (224, 224, 3) tidak sesuai dengan representasi gambar yang umum digunakan dalam machine learning, di mana gambar biasanya diwakili sebagai tensor dengan dimensi (batch_size, channels, height, width). Jika Anda ingin menciptakan tensor gambar dengan ukuran (224, 224, 3), sebaiknya gunakan dimensi yang benar, misalnya, (1, 3, 224, 224) jika ini adalah satu gambar.

### Zeros and ones

Sometimes you'll just want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

Let's create a tensor full of zeros with [`torch.zeros()`](https://pytorch.org/docs/stable/generated/torch.zeros.html)

Again, the `size` parameter comes into play.

In [16]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

Kode di atas menciptakan sebuah tensor dengan semua elemen bernilai nol, menggunakan PyTorch. Berikut adalah penjelasan singkat:

torch.zeros(size=(3, 4)): Membuat tensor dengan semua elemen bernilai nol dan ukuran (shape) (3, 4). Fungsi torch.zeros() menghasilkan tensor dengan elemen-elemen nol. Parameter size digunakan untuk menentukan ukuran tensor yang diinginkan.

zeros: Variabel yang menampung tensor nol yang baru dibuat.

zeros.dtype: Mengakses properti dtype dari tensor untuk mendapatkan tipe data (dtype) tensor tersebut. Properti ini memberikan informasi tentang tipe data elemen dalam tensor.

Baris terakhir dari kode tersebut adalah untuk mencetak atau menampilkan nilai tensor nol dan tipe datanya. Jika Anda mengeksekusi kode ini, Anda akan melihat keluaran yang berisi tensor dengan elemen-elemen nol dan tipe data tensor tersebut.
Ini menunjukkan tensor dengan ukuran (3, 4) yang terdiri dari elemen-elemen nol dan memiliki tipe data elemen float32. Pastikan bahwa variabel zeros telah didefinisikan sebelumnya untuk menjalankan kode ini.

We can do the same to create a tensor of all ones except using [`torch.ones()` ](https://pytorch.org/docs/stable/generated/torch.ones.html) instead.

In [17]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

Kode di atas menciptakan sebuah tensor dengan semua elemen bernilai satu, menggunakan PyTorch. Berikut adalah penjelasan singkat:

torch.ones(size=(3, 4)): Membuat tensor dengan semua elemen bernilai satu dan ukuran (shape) (3, 4). Fungsi torch.ones() menghasilkan tensor dengan elemen-elemen satu. Parameter size digunakan untuk menentukan ukuran tensor yang diinginkan.

ones: Variabel yang menampung tensor satu yang baru dibuat.

ones.dtype: Mengakses properti dtype dari tensor untuk mendapatkan tipe data (dtype) tensor tersebut. Properti ini memberikan informasi tentang tipe data elemen dalam tensor.

Baris terakhir dari kode tersebut adalah untuk mencetak atau menampilkan nilai tensor satu dan tipe datanya. Jika Anda mengeksekusi kode ini, Anda akan melihat keluaran yang berisi tensor dengan elemen-elemen satu dan tipe data tensor tersebut.
Ini menunjukkan tensor dengan ukuran (3, 4) yang terdiri dari elemen-elemen satu dan memiliki tipe data elemen float32. Pastikan bahwa variabel ones telah didefinisikan sebelumnya untuk menjalankan kode ini.

### Creating a range and tensors like

Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use `torch.arange(start, end, step)` to do so.

Where:
* `start` = start of range (e.g. 0)
* `end` = end of range (e.g. 10)
* `step` = how many steps in between each value (e.g. 1)

> **Note:** In Python, you can use `range()` to create a range. However in PyTorch, `torch.range()` is deprecated and may show an error in the future.

In [18]:
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

<ipython-input-18-a09072c806d9>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Kode di atas menciptakan tensor yang berisi rentang nilai dari 0 hingga 9 menggunakan dua metode berbeda: torch.range() yang sudah tidak direkomendasikan (deprecated) dan torch.arange(). Berikut adalah penjelasan singkat:

torch.range(0, 10): Metode ini sebelumnya digunakan untuk membuat tensor yang berisi rentang nilai dari 0 hingga 10, namun metode ini sudah tidak direkomendasikan (deprecated). Catatan: ini mungkin menghasilkan kesalahan di masa depan karena telah di-deprecate.

torch.arange(start=0, end=10, step=1): Metode ini lebih disarankan untuk membuat tensor yang berisi rentang nilai. torch.arange() memungkinkan Anda menentukan nilai awal (start), nilai akhir (end), dan langkah (step) untuk membuat rentang nilai.

zero_to_ten: Variabel yang menampung tensor yang baru dibuat menggunakan torch.arange().

Baris terakhir dari kode tersebut adalah untuk mencetak atau menampilkan nilai tensor yang berisi rentang nilai dari 0 hingga 9.
Dalam hal ini, zero_to_ten akan berisi tensor dengan nilai-nilai yang membentuk rentang dari 0 hingga 9 (tidak termasuk 10) dengan langkah 1. Pastikan bahwa Anda menggunakan torch.arange() sebagai pengganti torch.range() yang sudah di-deprecate.

Sometimes you might want one tensor of a certain type with the same shape as another tensor.

For example, a tensor of all zeros with the same shape as a previous tensor.

To do so you can use [`torch.zeros_like(input)`](https://pytorch.org/docs/stable/generated/torch.zeros_like.html) or [`torch.ones_like(input)`](https://pytorch.org/docs/1.9.1/generated/torch.ones_like.html) which return a tensor filled with zeros or ones in the same shape as the `input` respectively.

In [19]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Kode di atas menciptakan sebuah tensor yang berisi nol dan memiliki bentuk (shape) yang sama dengan tensor lain (zero_to_ten). Berikut adalah penjelasan singkat:

torch.zeros_like(input=zero_to_ten): Metode ini membuat tensor dengan elemen-elemen nol dan bentuk yang sama dengan tensor yang diberikan sebagai argumen (dalam hal ini, zero_to_ten). Fungsi ini memungkinkan pembuatan tensor dengan nol yang memiliki bentuk yang sesuai dengan tensor referensi.

ten_zeros: Variabel yang menampung tensor nol yang baru dibuat, dengan bentuk yang sama seperti tensor zero_to_ten.

Baris terakhir dari kode tersebut adalah untuk mencetak atau menampilkan nilai tensor yang berisi elemen-elemen nol dan memiliki bentuk yang sama dengan tensor referensi (zero_to_ten).

Contoh output yang diharapkan dari ten_zeros akan memiliki bentuk yang sama seperti zero_to_ten dan elemen-elemen berisi nol
Ini menunjukkan tensor dengan bentuk yang sesuai dengan zero_to_ten dan elemen-elemen yang semuanya nol. Pastikan bahwa variabel zero_to_ten telah didefinisikan sebelumnya untuk menjalankan kode ini.

### Tensor datatypes

There are many different [tensor datatypes available in PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types).

Some are specific for CPU and some are better for GPU.

Getting to know which is which can take some time.

Generally if you see `torch.cuda` anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is `torch.float32` or `torch.float`.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (`torch.float16` or `torch.half`) and 64-bit floating point (`torch.float64` or `torch.double`).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

Plus more!

> **Note:** An integer is a flat round number like `7` whereas a float has a decimal `7.0`.

The reason for all of these is to do with **precision in computing**.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

> **Resources:**
  * See the [PyTorch documentation for a list of all available tensor datatypes](https://pytorch.org/docs/stable/tensors.html#data-types).
  * Read the [Wikipedia page for an overview of what precision in computing](https://en.wikipedia.org/wiki/Precision_(computer_science)) is.

Let's see how to create some tensors with specific datatypes. We can do so using the `dtype` parameter.

In [20]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))



User
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)
perbaiki error pada kode diatas dengan error
RuntimeError                              Traceback (most recent call last)
<ipython-input-38-aceec990e652> in <cell line: 10>()
      8                          [9, 12]], dtype=torch.float32)
      9
---> 10 torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)
ChatGPT
Error ini muncul karena ketidakcocokan bentuk (shape) tensor yang dioperasikan oleh fungsi torch.matmul. Untuk mengatasi error ini, kita perlu mengubah bentuk salah satu tensor sehingga memenuhi persyaratan perkalian matriks.

Berikut adalah cara memperbaiki error tersebut dengan mengubah bentuk tensor_B menjadi matriks transpose:

python
Copy code
import torch

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

# Transpose tensor_B to make the matrix multiplication valid
tensor_B_transposed = torch.transpose(tensor_B, 0, 1)

result = torch.matmul(tensor_A, tensor_B_transposed)

print(result)
Dengan melakukan transposisi tensor_B menggunakan torch.transpose(tensor_B, 0, 1), kita mengubah bentuk tensor_B dari (3x2) menjadi (2x3), sehingga dapat dioperasikan dengan tensor_A yang memiliki bentuk (3x2).

User
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()
perbaiki kode diatas dengan error
TypeError                                 Traceback (most recent call last)
<ipython-input-77-53175578f49e> in <cell line: 2>()
      1 # If tensor is on GPU, can't transform it to NumPy (this will error)
----> 2 tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
ChatGPT
Error tersebut terjadi karena Anda mencoba mengonversi tensor yang berada di GPU (cuda:0) langsung menjadi NumPy array. Untuk memperbaiki ini, Anda perlu memindahkan tensor dari GPU ke CPU terlebih dahulu, dan baru kemudian mengonversikannya menjadi NumPy array.

Berikut adalah cara memperbaiki kodenya:

python
Copy code
import torch

# Contoh tensor di GPU
tensor_on_gpu = torch.tensor([1, 2, 3], device='cuda:0')

# Memindahkan tensor dari GPU ke CPU
tensor_on_cpu = tensor_on_gpu.cpu()

# Mengonversi tensor yang berada di CPU menjadi NumPy array
numpy_array = tensor_on_cpu.numpy()

print(numpy_array)
Dalam contoh di atas, cpu() digunakan untuk memindahkan tensor dari GPU ke CPU, dan setelah itu, Anda dapat menggunakan numpy() untuk mengonversikannya menjadi NumPy array.

User
import torch
torch.__version__
berikan penjelasan mengenai kode diatas
ChatGPT
Kode di atas menggunakan modul PyTorch untuk mencetak versi PyTorch yang sedang digunakan. Berikut adalah penjelasan singkat:

import torch: Ini mengimpor modul PyTorch ke dalam skrip atau lingkungan kerja Python Anda.

torch.__version__: Ini adalah properti yang memberikan versi PyTorch yang sedang digunakan. Dengan menjalankan torch.__version__, Anda dapat melihat versi PyTorch yang terpasang pada sistem Anda.

Anda dapat mengeksekusi kode ini untuk mendapatkan versi PyTorch yang sedang Anda gunakan dalam lingkungan Python Anda saat ini. Misalnya, hasilnya bisa seperti "1.8.1" atau versi lainnya, tergantung pada versi PyTorch yang Anda miliki diinstal.

User
# Scalar
scalar = torch.tensor(7)
scalar
Berikan penjelasan dari kode diatas
ChatGPT
Kode di atas membuat sebuah tensor skalar menggunakan PyTorch. Berikut adalah penjelasan singkat:

torch.tensor(7): Membuat tensor skalar dengan nilai 7. Sebuah tensor skalar adalah tensor dengan hanya satu elemen atau nilai tunggal. Dalam konteks ini, tensor ini hanya berisi angka 7.

scalar: Variabel yang menampung tensor skalar tersebut.

scalar: Baris terakhir dari kode tersebut adalah untuk mencetak atau menampilkan nilai tensor skalar. Jika Anda mengeksekusi kode ini, Anda akan melihat keluaran yang berisi nilai skalar yang ditentukan, yaitu 7.

Jadi, secara keseluruhan, kode ini mengilustrasikan cara membuat tensor skalar menggunakan PyTorch dan menyimpannya dalam variabel scalar.

User
scalar.ndim
berikan penjelasan dari kode diatas
ChatGPT
Dalam PyTorch, tensor skalar (tensor dengan hanya satu elemen) merupakan tensor 0 dimensi (dimensi nol). Kode scalar.ndim mencoba mengakses atribut ndim dari tensor scalar untuk mendapatkan jumlah dimensi tensor tersebut.

Namun, tensor skalar dalam PyTorch tidak memiliki atribut ndim karena dimensinya adalah 0. Sebagai gantinya, kita dapat menggunakan metode dim() untuk mendapatkan jumlah dimensi dari tensor. Contoh:

python
Copy code
scalar = torch.tensor(7)
print(scalar.dim())  # Output: 0
Dengan menggunakan dim(), kita dapat mengetahui bahwa tensor skalar memiliki 0 dimensi. Jadi, jika Anda menjalankan scalar.ndim, itu akan menghasilkan kesalahan karena atribut ndim tidak ditemukan pada tensor skalar dalam PyTorch.

User
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()
berikan penjelasan dari kode diatas
ChatGPT
Kode di atas menggunakan metode .item() pada tensor skalar untuk mendapatkan nilai Python yang terkandung di dalam tensor tersebut. Berikut adalah penjelasan singkat:

scalar: Ini adalah tensor skalar yang telah dibuat sebelumnya. Dalam contoh ini, diasumsikan bahwa scalar adalah tensor skalar yang berisi satu elemen.

.item(): Metode ini digunakan untuk mengambil nilai Python dari tensor skalar. Dikarenakan tensor skalar hanya berisi satu elemen, metode ini dapat digunakan untuk mendapatkan nilai tersebut sebagai nilai Python biasa (int, float, dll.).

Contoh penggunaan:

python
Copy code
scalar = torch.tensor(7)
python_number = scalar.item()
print(python_number)
Dalam hal ini, python_number akan berisi nilai Python 7, karena tensor skalar hanya memiliki satu elemen dan .item() digunakan untuk mengakses nilai tersebut dalam bentuk Python. Penting untuk dicatat bahwa .item() hanya berlaku untuk tensor dengan satu elemen. Jika tensor memiliki lebih dari satu elemen, penggunaan .item() akan menghasilkan kesalahan.

User
# Vector
vector = torch.tensor([7, 7])
vector
berikan penjelasan dari kode diatas
ChatGPT
Kode di atas membuat sebuah tensor vektor menggunakan PyTorch. Berikut adalah penjelasan singkat:

torch.tensor([7, 7]): Membuat tensor vektor dengan dua elemen, yaitu 7 dan 7. Sebuah tensor vektor adalah tensor satu dimensi yang berisi sejumlah elemen.

vector: Variabel yang menampung tensor vektor tersebut.

vector: Baris terakhir dari kode tersebut adalah untuk mencetak atau menampilkan nilai tensor vektor. Jika Anda mengeksekusi kode ini, Anda akan melihat keluaran yang berisi nilai vektor yang ditentukan, yaitu [7, 7].

Jadi, secara keseluruhan, kode ini mengilustrasikan cara membuat tensor vektor dengan dua elemen menggunakan PyTorch dan menyimpannya dalam variabel vector.

User
# Check the number of dimensions of vector
vector.ndim
ChatGPT
Dalam PyTorch, tensor vektor (tensor satu dimensi) memiliki satu dimensi. Kode vector.ndim mencoba untuk mengakses atribut ndim dari tensor vector untuk mendapatkan jumlah dimensi tensor tersebut.

Namun, tensor vektor dalam PyTorch sebenarnya tidak memiliki atribut ndim, karena dimensinya sudah terdefinisi sebagai satu dimensi. Sebagai gantinya, kita dapat menggunakan metode dim() untuk mendapatkan jumlah dimensi dari tensor. Contoh:

python
Copy code
vector = torch.tensor([7, 7])
print(vector.dim())  # Output: 1
Dengan menggunakan dim(), kita dapat mengetahui bahwa tensor vektor memiliki satu dimensi. Jadi, jika Anda menjalankan vector.ndim, itu mungkin menghasilkan kesalahan karena atribut ndim tidak ditemukan pada tensor vektor dalam PyTorch. Sebaiknya, gunakan metode dim() untuk mendapatkan jumlah dimensi.

User
# Check shape of vector
vector.shape
ChatGPT
Untuk mendapatkan bentuk (shape) dari tensor dalam PyTorch, Anda dapat menggunakan atribut shape. Namun, perlu diingat bahwa untuk tensor satu dimensi seperti vektor, hasilnya akan disajikan dalam bentuk tupel dengan satu elemen.

Berikut adalah contoh penggunaan untuk mendapatkan bentuk dari tensor vektor:

python
Copy code
import torch

vector = torch.tensor([7, 7])
print(vector.shape)
Output yang diharapkan dari kode ini adalah (2,). Ini menunjukkan bahwa vektor memiliki dua elemen dan merupakan tensor satu dimensi. Jadi, bentuknya adalah tupel dengan satu elemen yang menyatakan panjang vektor.


2 / 2

User
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX
ChatGPT
Kode di atas membuat sebuah tensor matriks menggunakan PyTorch. Berikut adalah penjelasan singkat:

torch.tensor([[7, 8], [9, 10]]): Membuat tensor matriks dengan dua baris dan dua kolom. Sebuah tensor matriks adalah tensor dua dimensi yang berisi elemen-elemen ini.

MATRIX: Variabel yang menampung tensor matriks tersebut.

MATRIX: Baris terakhir dari kode tersebut adalah untuk mencetak atau menampilkan nilai tensor matriks. Jika Anda mengeksekusi kode ini, Anda akan melihat keluaran yang berisi nilai matriks yang ditentukan.

Jadi, secara keseluruhan, kode ini mengilustrasikan cara membuat tensor matriks dengan elemen-elemen tertentu menggunakan PyTorch dan menyimpannya dalam variabel MATRIX.

User
# Check number of dimensions
MATRIX.ndim
ChatGPT
Untuk mendapatkan jumlah dimensi dari tensor dalam PyTorch, Anda dapat menggunakan metode dim() atau properti ndim. Namun, perlu diingat bahwa matriks adalah tensor dua dimensi.

Berikut adalah contoh penggunaan untuk mendapatkan jumlah dimensi dari tensor matriks:

python
Copy code
import torch

MATRIX = torch.tensor([[7, 8], [9, 10]])
print(MATRIX.dim())  # Output: 2
Hasil dari MATRIX.dim() adalah 2, yang menunjukkan bahwa matriks memiliki dua dimensi. Jika Anda ingin menggunakan ndim, Anda dapat menggantinya dengan MATRIX.ndim, dan itu juga akan menghasilkan 2.

User
MATRIX.shape
ChatGPT
Untuk mendapatkan bentuk (shape) dari tensor matriks dalam PyTorch, Anda dapat menggunakan atribut shape. Berikut adalah contoh penggunaan:

python
Copy code
import torch

MATRIX = torch.tensor([[7, 8], [9, 10]])
print(MATRIX.shape)
Output yang diharapkan dari kode ini adalah (2, 2). Ini menunjukkan bahwa matriks memiliki dua dimensi, dengan dua elemen dalam dimensi pertama (baris) dan dua elemen dalam dimensi kedua (kolom). Jadi, bentuknya adalah tupel (2, 2).

User
# Check number of dimensions for TENSOR
TENSOR.ndim
ChatGPT
It appears that the variable TENSOR is not defined in the provided context, so attempting to access its number of dimensions using TENSOR.ndim may result in an error. In PyTorch, you can use the dim() method or the ndim property to check the number of dimensions of a tensor.

Here's an example assuming TENSOR is a PyTorch tensor:

python
Copy code
import torch

# Assuming TENSOR is a defined tensor
TENSOR = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Check number of dimensions
print(TENSOR.dim())  # Output: 2
# Alternatively,
print(TENSOR.ndim)   # Output: 2
Make sure to replace the placeholder TENSOR with the actual tensor you are working with. The provided code will work if TENSOR is a valid PyTorch tensor.

User
terjemahkan
ChatGPT
Nampaknya variabel TENSOR tidak didefinisikan dalam konteks yang diberikan, sehingga mencoba mengakses jumlah dimensinya menggunakan TENSOR.ndim mungkin menghasilkan kesalahan. Dalam PyTorch, Anda dapat menggunakan metode dim() atau properti ndim untuk memeriksa jumlah dimensi dari suatu tensor.

Berikut adalah contoh jika TENSOR adalah tensor PyTorch yang terdefinisi:

python
Copy code
import torch

# Asumsikan TENSOR adalah tensor yang terdefinisi
TENSOR = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Periksa jumlah dimensi
print(TENSOR.dim())  # Output: 2
# Atau,
print(TENSOR.ndim)   # Output: 2
Pastikan untuk menggantikan placeholder TENSOR dengan tensor yang sesungguhnya sedang Anda kerjakan. Kode yang diberikan akan berfungsi jika TENSOR adalah tensor PyTorch yang valid.

User
# Check shape of TENSOR
TENSOR.shape
ChatGPT
Dalam PyTorch, untuk mendapatkan bentuk (shape) dari suatu tensor, Anda dapat menggunakan atribut shape. Berikut adalah contoh penggunaan:

python
Copy code
import torch

# Asumsikan TENSOR adalah tensor yang terdefinisi
TENSOR = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Periksa bentuk (shape) dari tensor
print(TENSOR.shape)
Output yang diharapkan dari kode ini adalah bentuk tensor, contohnya (2, 3). Ini menunjukkan bahwa tensor tersebut memiliki dua dimensi, dengan dua elemen dalam dimensi pertama (baris) dan tiga elemen dalam dimensi kedua (kolom). Jadi, bentuknya adalah tupel (2, 3). Pastikan untuk menggantikan placeholder TENSOR dengan tensor yang sesungguhnya sedang Anda kerjakan.

User
Berikan penjelasan dari kode
# Check shape of TENSOR
TENSOR.shape
ChatGPT
Kode di atas bertujuan untuk menampilkan bentuk (shape) dari suatu tensor yang disimpan dalam variabel TENSOR menggunakan atribut shape. Berikut adalah penjelasan singkat:

TENSOR: Ini adalah variabel yang mengacu pada suatu tensor PyTorch yang sudah didefinisikan sebelumnya.

.shape: Atribut ini digunakan untuk mendapatkan bentuk (shape) dari tensor. Bentuk tensor mencakup informasi tentang jumlah dimensi dan ukuran masing-masing dimensi.

TENSOR.shape: Eksekusi perintah ini akan mengembalikan bentuk tensor yang diakses melalui atribut shape. Outputnya berupa tupel yang menyatakan jumlah elemen dalam setiap dimensi.

Contoh output bisa berupa (2, 3), yang berarti tensor tersebut memiliki dua dimensi dengan dua elemen dalam dimensi pertama dan tiga elemen dalam dimensi kedua. Pastikan bahwa variabel TENSOR telah didefinisikan sebagai tensor PyTorch sebelumnya untuk menjalankan kode ini.

User
berikan penjelasan dari kode
MATRIX.shape
ChatGPT
Kode MATRIX.shape bertujuan untuk menampilkan bentuk (shape) dari suatu tensor matriks yang disimpan dalam variabel MATRIX. Berikut adalah penjelasan singkat:

MATRIX: Ini adalah variabel yang mengacu pada suatu tensor matriks PyTorch yang sudah didefinisikan sebelumnya.

.shape: Atribut ini digunakan untuk mendapatkan bentuk (shape) dari tensor. Bentuk tensor mencakup informasi tentang jumlah dimensi dan ukuran masing-masing dimensi.

MATRIX.shape: Eksekusi perintah ini akan mengembalikan bentuk tensor yang diakses melalui atribut shape. Outputnya berupa tupel yang menyatakan jumlah elemen dalam setiap dimensi.

Contoh output bisa berupa (2, 2), yang berarti matriks tersebut memiliki dua dimensi dengan dua elemen dalam setiap dimensinya. Pastikan bahwa variabel MATRIX telah didefinisikan sebagai tensor matriks PyTorch sebelumnya untuk menjalankan kode ini.

User
berikan penjelasan dari kode
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR
ChatGPT
Kode di atas menciptakan sebuah tensor tiga dimensi menggunakan PyTorch dan kemudian menampilkan nilai tensor tersebut. Berikut adalah penjelasan singkat:

torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]]): Membuat tensor tiga dimensi dengan nilai yang diberikan. Dalam hal ini, tensor tersebut memiliki tiga dimensi: satu dimensi untuk "tumpukan" lapisan, satu dimensi untuk baris, dan satu dimensi untuk kolom.

TENSOR: Variabel yang menampung tensor tiga dimensi yang baru dibuat.

TENSOR: Baris terakhir dari kode tersebut adalah untuk mencetak atau menampilkan nilai tensor tersebut. Jika Anda mengeksekusi kode ini, Anda akan melihat keluaran yang berisi nilai tensor tiga dimensi yang ditentukan.

Contoh output bisa terlihat seperti:

lua
Copy code
tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
Ini menunjukkan bahwa tensor tersebut memiliki tiga dimensi, dengan ukuran masing-masing dimensinya adalah 1, 3, dan 3. Pastikan bahwa variabel TENSOR telah didefinisikan sebagai tensor PyTorch sebelumnya untuk menjalankan kode ini.

User
berikan penjelasan dari kode
# Check number of dimensions for TENSOR
TENSOR.ndim
ChatGPT
Kode TENSOR.ndim mencoba untuk mengecek jumlah dimensi dari tensor yang disimpan dalam variabel TENSOR menggunakan properti ndim. Namun, perlu dicatat bahwa properti ndim tidak langsung tersedia pada objek tensor di PyTorch.

Dalam PyTorch, untuk mendapatkan jumlah dimensi dari suatu tensor, Anda dapat menggunakan metode dim() atau properti ndim. Berikut adalah contoh penggunaan metode dim():

python
Copy code
import torch

# Asumsikan TENSOR adalah tensor yang terdefinisi
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])

# Periksa jumlah dimensi
print(TENSOR.dim())  # Output: 3
Hasil dari TENSOR.dim() adalah 3, yang menunjukkan bahwa tensor tersebut memiliki tiga dimensi. Properti ndim tidak umum digunakan dalam konteks PyTorch, jadi sebaiknya menggunakan metode dim() untuk memeriksa jumlah dimensi dari suatu tensor.

User
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype
berikan penjelasan dari kode diatas
ChatGPT
Kode di atas menciptakan sebuah tensor acak dengan ukuran (3, 4) menggunakan PyTorch. Berikut adalah penjelasan singkat:

torch.rand(size=(3, 4)): Membuat tensor acak dengan ukuran (3, 4). Fungsi torch.rand() menghasilkan tensor dengan nilai acak yang terdistribusi seragam antara 0 dan 1. Parameter size digunakan untuk menentukan ukuran tensor yang diinginkan.

random_tensor: Variabel yang menampung tensor acak yang baru dibuat.

random_tensor.dtype: Mengakses properti dtype dari tensor untuk mendapatkan tipe data (dtype) tensor tersebut. Properti ini memberikan informasi tentang tipe data elemen dalam tensor.

Baris terakhir dari kode tersebut adalah untuk mencetak atau menampilkan nilai tensor acak dan tipe datanya. Jika Anda mengeksekusi kode ini, Anda akan melihat keluaran yang berisi nilai-nilai acak dan tipe data tensor tersebut.

Contoh output bisa terlihat seperti:

lua
Copy code
tensor([[0.1234, 0.5678, 0.8901, 0.2345],
        [0.6789, 0.0123, 0.4567, 0.8901],
        [0.2345, 0.6789, 0.0123, 0.4567]]), torch.float32
Ini menunjukkan tensor acak dengan ukuran (3, 4) dan tipe data elemen float32. Pastikan bahwa variabel random_tensor telah didefinisikan sebelumnya untuk menjalankan kode ini.

User
berikan penjelasan dari kode
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim
ChatGPT
Kode di atas menciptakan sebuah tensor acak dengan ukuran (224, 224, 3) menggunakan PyTorch. Namun, perlu dicatat bahwa hal ini dapat menyebabkan masalah karena ukuran ini tidak sesuai dengan konvensi untuk representasi gambar dalam bentuk tensor.

Berikut adalah penjelasan singkat:

torch.rand(size=(224, 224, 3)): Membuat tensor acak dengan ukuran (224, 224, 3). Fungsi torch.rand() menghasilkan tensor dengan nilai acak yang terdistribusi seragam antara 0 dan 1. Parameter size digunakan untuk menentukan ukuran tensor yang diinginkan.

random_image_size_tensor: Variabel yang menampung tensor acak yang baru dibuat.

random_image_size_tensor.shape: Mengakses atribut shape dari tensor untuk mendapatkan bentuk (shape) tensor tersebut. Bentuk tensor memberikan informasi tentang jumlah dimensi dan ukuran masing-masing dimensi.

random_image_size_tensor.ndim: Mengakses metode ndim dari tensor untuk mendapatkan jumlah dimensi tensor tersebut.

Baris terakhir dari kode tersebut adalah untuk mencetak atau menampilkan bentuk dan jumlah dimensi tensor. Jika Anda mengeksekusi kode ini, Anda akan melihat keluaran yang berisi bentuk dan jumlah dimensi tensor tersebut.

Perlu dicatat bahwa ukuran (224, 224, 3) tidak sesuai dengan representasi gambar yang umum digunakan dalam machine learning, di mana gambar biasanya diwakili sebagai tensor dengan dimensi (batch_size, channels, height, width). Jika Anda ingin menciptakan tensor gambar dengan ukuran (224, 224, 3), sebaiknya gunakan dimensi yang benar, misalnya, (1, 3, 224, 224) jika ini adalah satu gambar.

User
berikan penjelasan dari kode
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype
ChatGPT
Kode di atas menciptakan sebuah tensor dengan semua elemen bernilai nol, menggunakan PyTorch. Berikut adalah penjelasan singkat:

torch.zeros(size=(3, 4)): Membuat tensor dengan semua elemen bernilai nol dan ukuran (shape) (3, 4). Fungsi torch.zeros() menghasilkan tensor dengan elemen-elemen nol. Parameter size digunakan untuk menentukan ukuran tensor yang diinginkan.

zeros: Variabel yang menampung tensor nol yang baru dibuat.

zeros.dtype: Mengakses properti dtype dari tensor untuk mendapatkan tipe data (dtype) tensor tersebut. Properti ini memberikan informasi tentang tipe data elemen dalam tensor.

Baris terakhir dari kode tersebut adalah untuk mencetak atau menampilkan nilai tensor nol dan tipe datanya. Jika Anda mengeksekusi kode ini, Anda akan melihat keluaran yang berisi tensor dengan elemen-elemen nol dan tipe data tensor tersebut.

Contoh output bisa terlihat seperti:

lua
Copy code
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]), torch.float32
Ini menunjukkan tensor dengan ukuran (3, 4) yang terdiri dari elemen-elemen nol dan memiliki tipe data elemen float32. Pastikan bahwa variabel zeros telah didefinisikan sebelumnya untuk menjalankan kode ini.

User
berikan penjelasan dari kode
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype
ChatGPT
Kode di atas menciptakan sebuah tensor dengan semua elemen bernilai satu, menggunakan PyTorch. Berikut adalah penjelasan singkat:

torch.ones(size=(3, 4)): Membuat tensor dengan semua elemen bernilai satu dan ukuran (shape) (3, 4). Fungsi torch.ones() menghasilkan tensor dengan elemen-elemen satu. Parameter size digunakan untuk menentukan ukuran tensor yang diinginkan.

ones: Variabel yang menampung tensor satu yang baru dibuat.

ones.dtype: Mengakses properti dtype dari tensor untuk mendapatkan tipe data (dtype) tensor tersebut. Properti ini memberikan informasi tentang tipe data elemen dalam tensor.

Baris terakhir dari kode tersebut adalah untuk mencetak atau menampilkan nilai tensor satu dan tipe datanya. Jika Anda mengeksekusi kode ini, Anda akan melihat keluaran yang berisi tensor dengan elemen-elemen satu dan tipe data tensor tersebut.

Contoh output bisa terlihat seperti:

lua
Copy code
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]), torch.float32
Ini menunjukkan tensor dengan ukuran (3, 4) yang terdiri dari elemen-elemen satu dan memiliki tipe data elemen float32. Pastikan bahwa variabel ones telah didefinisikan sebelumnya untuk menjalankan kode ini.

User
berikan penjelasan dari kode
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten
ChatGPT
Kode di atas menciptakan tensor yang berisi rentang nilai dari 0 hingga 9 menggunakan dua metode berbeda: torch.range() yang sudah tidak direkomendasikan (deprecated) dan torch.arange(). Berikut adalah penjelasan singkat:

torch.range(0, 10): Metode ini sebelumnya digunakan untuk membuat tensor yang berisi rentang nilai dari 0 hingga 10, namun metode ini sudah tidak direkomendasikan (deprecated). Catatan: ini mungkin menghasilkan kesalahan di masa depan karena telah di-deprecate.

torch.arange(start=0, end=10, step=1): Metode ini lebih disarankan untuk membuat tensor yang berisi rentang nilai. torch.arange() memungkinkan Anda menentukan nilai awal (start), nilai akhir (end), dan langkah (step) untuk membuat rentang nilai.

zero_to_ten: Variabel yang menampung tensor yang baru dibuat menggunakan torch.arange().

Baris terakhir dari kode tersebut adalah untuk mencetak atau menampilkan nilai tensor yang berisi rentang nilai dari 0 hingga 9.

Contoh output yang diharapkan dari zero_to_ten adalah:

scss
Copy code
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Dalam hal ini, zero_to_ten akan berisi tensor dengan nilai-nilai yang membentuk rentang dari 0 hingga 9 (tidak termasuk 10) dengan langkah 1. Pastikan bahwa Anda menggunakan torch.arange() sebagai pengganti torch.range() yang sudah di-deprecate.

User
berikan penjelasan dari kode
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros
ChatGPT
Kode di atas menciptakan sebuah tensor yang berisi nol dan memiliki bentuk (shape) yang sama dengan tensor lain (zero_to_ten). Berikut adalah penjelasan singkat:

torch.zeros_like(input=zero_to_ten): Metode ini membuat tensor dengan elemen-elemen nol dan bentuk yang sama dengan tensor yang diberikan sebagai argumen (dalam hal ini, zero_to_ten). Fungsi ini memungkinkan pembuatan tensor dengan nol yang memiliki bentuk yang sesuai dengan tensor referensi.

ten_zeros: Variabel yang menampung tensor nol yang baru dibuat, dengan bentuk yang sama seperti tensor zero_to_ten.

Baris terakhir dari kode tersebut adalah untuk mencetak atau menampilkan nilai tensor yang berisi elemen-elemen nol dan memiliki bentuk yang sama dengan tensor referensi (zero_to_ten).

Contoh output yang diharapkan dari ten_zeros akan memiliki bentuk yang sama seperti zero_to_ten dan elemen-elemen berisi nol, misalnya:

scss
Copy code
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
Ini menunjukkan tensor dengan bentuk yang sesuai dengan zero_to_ten dan elemen-elemen yang semuanya nol. Pastikan bahwa variabel zero_to_ten telah didefinisikan sebelumnya untuk menjalankan kode ini.

User
berikan penjelasan dari kode
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device
ChatGPT
Kode di atas menciptakan tensor PyTorch yang berisi nilai float dengan tipe data float32 dan konfigurasi tambahan seperti bentuk (shape), perangkat (device), dan apakah gradient perlu dihitung atau tidak. Berikut adalah penjelasan singkat:

torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False): Membuat tensor dengan elemen-elemen [3.0, 6.0, 9.0]. Argumen dtype digunakan untuk menentukan tipe data tensor, dan dalam kasus ini, diatur menjadi None, yang akan mengikuti default (torch.float32 atau tipe data apapun yang diberikan). Argumen device juga diatur menjadi None, yang berarti tensor akan dibuat di perangkat yang sesuai dengan konfigurasi default. Argumen requires_grad diatur menjadi False, yang berarti tensor tidak akan mencatat gradient saat operasi dijalankan pada tensor ini.

float_32_tensor: Variabel yang menampung tensor yang baru dibuat.

float_32_tensor.shape: Mengakses atribut shape dari tensor untuk mendapatkan bentuk (shape) tensor tersebut.

float_32_tensor.dtype: Mengakses properti dtype dari tensor untuk mendapatkan tipe data (dtype) tensor tersebut.

float_32_tensor.device: Mengakses properti device dari tensor untuk mendapatkan informasi perangkat di mana tensor ini ditempatkan.

Baris terakhir dari kode tersebut adalah untuk mencetak atau menampilkan bentuk, tipe data, dan perangkat tensor.

Contoh output yang diharapkan bisa terlihat seperti:
(torch.Size([3]), torch.float32, 'cpu')
Ini menunjukkan bahwa tensor memiliki bentuk dengan satu dimensi dan panjang 3, memiliki tipe data float32, dan ditempatkan di perangkat CPU ('cpu'). Pastikan bahwa variabel float_32_tensor telah didefinisikan sebelumnya untuk menjalankan kode ini.

Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

For example, one of tensors is `torch.float32` and the other is `torch.float16` (PyTorch often likes tensors to be the same format).

Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

We'll see more of this device talk later on.

For now let's create a tensor with `dtype=torch.float16`.

In [21]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

Kode di atas menciptakan tensor PyTorch yang berisi nilai float dengan tipe data float16 (torch.float16 atau torch.half). Berikut adalah penjelasan singkat:

torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16): Membuat tensor dengan elemen-elemen [3.0, 6.0, 9.0] dan menetapkan tipe data tensor sebagai float16. Argumen dtype digunakan untuk secara eksplisit menentukan tipe data tensor, dan dalam hal ini diatur sebagai torch.float16.

float_16_tensor: Variabel yang menampung tensor yang baru dibuat.

float_16_tensor.dtype: Mengakses properti dtype dari tensor untuk mendapatkan tipe data (dtype) tensor tersebut.

Baris terakhir dari kode tersebut adalah untuk mencetak atau menampilkan tipe data tensor.

Contoh output yang diharapkan adalah:
torch.float16
Ini menunjukkan bahwa tensor memiliki tipe data float16. Penggunaan tipe data float16 dapat mengurangi penggunaan memori tetapi dengan presisi yang lebih rendah dibandingkan dengan float32. Pastikan bahwa variabel float_16_tensor telah didefinisikan sebelumnya untuk menjalankan kode ini.

## Getting information from tensors

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:
* `shape` - what shape is the tensor? (some operations require specific shape rules)
* `dtype` - what datatype are the elements within the tensor stored in?
* `device` - what device is the tensor stored on? (usually GPU or CPU)

Let's create a random tensor and find out details about it.

In [22]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.4578, 0.4633, 0.2290, 0.6807],
        [0.5562, 0.4106, 0.0170, 0.6215],
        [0.7874, 0.7462, 0.0439, 0.8934]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Kode di atas menciptakan tensor PyTorch dengan elemen-elemen yang dipilih secara acak dan kemudian mencetak atau menampilkan informasi tentang tensor tersebut. Berikut adalah penjelasan singkat:

torch.rand(3, 4): Membuat tensor dengan ukuran (shape) 3x4 yang berisi nilai acak yang terdistribusi seragam antara 0 dan 1. Fungsi torch.rand() digunakan untuk menciptakan tensor dengan nilai acak.

some_tensor: Variabel yang menampung tensor yang baru dibuat.

print(some_tensor): Mencetak atau menampilkan nilai tensor itu sendiri.

print(f"Shape of tensor: {some_tensor.shape}"): Mencetak atau menampilkan bentuk (shape) dari tensor. Bentuk tensor memberikan informasi tentang jumlah dimensi dan ukuran masing-masing dimensi.

print(f"Datatype of tensor: {some_tensor.dtype}"): Mencetak atau menampilkan tipe data (dtype) dari tensor. Tipe data tensor menentukan jenis nilai yang dapat dimiliki oleh tensor tersebut.

print(f"Device tensor is stored on: {some_tensor.device}"): Mencetak atau menampilkan perangkat (device) tempat tensor disimpan. Dalam contoh ini, perangkat akan secara default diatur ke CPU ('cpu').

Contoh output bisa terlihat seperti:

tensor([[0.1234, 0.5678, 0.8901, 0.2345],
        [0.6789, 0.0123, 0.4567, 0.8901],
        [0.2345, 0.6789, 0.0123, 0.4567]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
Ini menunjukkan tensor dengan nilai acak, bentuk (3, 4), tipe data float32, dan disimpan di perangkat CPU. Pastikan bahwa variabel some_tensor telah didefinisikan sebelumnya untuk menjalankan kode ini.

> **Note:** When you run into issues in PyTorch, it's very often one to do with one of the three attributes above. So when the error messages show up, sing yourself a little song called "what, what, where":
  * "*what shape are my tensors? what datatype are they and where are they stored? what shape, what datatype, where where where*"

## Manipulating tensors (tensor operations)

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).

### Basic operations

Let's start with a few of the fundamental operations, addition (`+`), subtraction (`-`), mutliplication (`*`).

They work just as you think they would.

In [23]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

Kode di atas menciptakan tensor PyTorch dengan nilai [1, 2, 3] dan kemudian menambahkan nilai 10 ke setiap elemen tensor. Berikut adalah penjelasan singkat:

torch.tensor([1, 2, 3]): Membuat tensor dengan elemen-elemen [1, 2, 3]. Fungsi torch.tensor() digunakan untuk membuat tensor dari suatu list atau array.

tensor + 10: Melakukan operasi penambahan pada setiap elemen tensor dengan nilai 10. PyTorch mendukung operasi matematika pada tensor, dan dalam hal ini, nilai 10 ditambahkan ke setiap elemen tensor.

Baris terakhir dari kode tersebut adalah untuk mengeksekusi operasi penambahan dan hasilnya ditampilkan.

Contoh output bisa terlihat seperti:
tensor([11, 12, 13])
Ini menunjukkan bahwa setiap elemen dalam tensor [1, 2, 3] telah ditambahkan dengan 10, menghasilkan tensor baru dengan nilai [11, 12, 13]. Pastikan bahwa variabel tensor telah didefinisikan sebelumnya untuk menjalankan kode ini.

In [24]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

Kode di atas mengambil tensor PyTorch yang sudah ada dengan nilai [1, 2, 3] dan mengalikan setiap elemennya dengan nilai 10. Berikut adalah penjelasan singkat:

tensor * 10: Melakukan operasi perkalian pada setiap elemen tensor dengan nilai 10. PyTorch mendukung operasi matematika pada tensor, dan dalam hal ini, setiap elemen tensor dikalikan dengan 10.

Baris terakhir dari kode tersebut adalah untuk mengeksekusi operasi perkalian dan menampilkan hasilnya.

Contoh output bisa terlihat seperti:
tensor([10, 20, 30])
Ini menunjukkan bahwa setiap elemen dalam tensor [1, 2, 3] telah dikalikan dengan 10, menghasilkan tensor baru dengan nilai [10, 20, 30]. Pastikan bahwa variabel tensor telah didefinisikan sebelumnya untuk menjalankan kode ini.

Notice how the tensor values above didn't end up being `tensor([110, 120, 130])`, this is because the values inside the tensor don't change unless they're reassigned.

In [25]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

Kode tersebut mencoba menampilkan nilai dari tensor yang telah diubah sebelumnya dengan operasi perkalian (dikali 10). Penjelasan singkatnya adalah:

tensor: Baris kode ini adalah untuk menampilkan nilai tensor tanpa melakukan reassign atau pengubahan nilai pada variabel. Hal ini mencoba menunjukkan bahwa operasi perkalian sebelumnya (tensor * 10) tidak secara permanen mengubah nilai tensor kecuali nilai tersebut diassign kembali ke variabel.
Contoh outputnya mungkin akan menunjukkan nilai tensor setelah operasi perkalian sebelumnya:
tensor([10, 20, 30])
Namun, penting untuk dicatat bahwa ini hanya menampilkan nilai tensor untuk keperluan pengamatan atau inspeksi sementara, dan nilai tensor sebenarnya tidak diubah kecuali variabel tensor diassign kembali dengan hasil operasi tersebut.

Let's subtract a number and this time we'll reassign the `tensor` variable.

In [26]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

Kode tersebut mengambil tensor yang telah dimodifikasi sebelumnya (hasil perkalian dengan 10) dan kemudian mengurangkan nilai 10 dari setiap elemennya. Berikut adalah penjelasan singkat:

tensor = tensor - 10: Melakukan operasi pengurangan pada setiap elemen tensor dengan nilai 10, dan kemudian menugaskan hasilnya kembali ke variabel tensor. Dengan melakukan ini, nilai tensor diperbarui dengan hasil pengurangan.

tensor: Baris ini adalah untuk menampilkan nilai tensor setelah operasi pengurangan dan reassign. Nilai tensor sekarang adalah nilai sebelumnya yang dikalikan dengan 10, kemudian dikurangkan dengan 10.

Contoh outputnya mungkin akan menunjukkan nilai tensor setelah operasi pengurangan dan reassign:
tensor([0, 10, 20])
Ini menunjukkan bahwa setiap elemen dalam tensor telah dikurangkan dengan 10, menghasilkan tensor baru dengan nilai [0, 10, 20]. Variabel tensor sekarang berisi nilai yang telah diperbarui.

In [27]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

Kode tersebut mengambil tensor yang telah dimodifikasi sebelumnya (hasil pengurangan dengan 10) dan kemudian menambahkan nilai 10 ke setiap elemennya. Berikut adalah penjelasan singkat:

tensor = tensor + 10: Melakukan operasi penambahan pada setiap elemen tensor dengan nilai 10, dan kemudian menugaskan hasilnya kembali ke variabel tensor. Dengan melakukan ini, nilai tensor diperbarui dengan hasil penambahan.

tensor: Baris ini adalah untuk menampilkan nilai tensor setelah operasi penambahan dan reassign. Nilai tensor sekarang adalah nilai sebelumnya yang telah dikurangkan dengan 10, kemudian ditambahkan dengan 10.

Contoh outputnya mungkin akan menunjukkan nilai tensor setelah operasi penambahan dan reassign:
tensor([10, 20, 30])
Ini menunjukkan bahwa setiap elemen dalam tensor telah ditambahkan dengan 10, menghasilkan tensor baru dengan nilai [10, 20, 30]. Variabel tensor sekarang berisi nilai yang telah diperbarui.

PyTorch also has a bunch of built-in functions like [`torch.mul()`](https://pytorch.org/docs/stable/generated/torch.mul.html#torch.mul) (short for multiplication) and [`torch.add()`](https://pytorch.org/docs/stable/generated/torch.add.html) to perform basic operations.

In [28]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

Kode tersebut mencoba mengalikan setiap elemen dari tensor tensor dengan nilai 10 menggunakan fungsi torch.multiply(). Namun, perlu dicatat bahwa fungsi tersebut sebenarnya tidak ada di PyTorch. Operasi perkalian pada tensor dalam PyTorch dapat dilakukan menggunakan operator * atau menggunakan fungsi-fungsi seperti torch.mul().

Berikut adalah penjelasan singkat:

torch.multiply(tensor, 10): Baris ini mencoba menggunakan fungsi torch.multiply() untuk mengalikan setiap elemen dari tensor tensor dengan nilai 10. Namun, fungsi torch.multiply() sebenarnya tidak ada di PyTorch.
Untuk melakukan operasi perkalian pada tensor dalam PyTorch, Anda dapat menggunakan operator * atau menggunakan fungsi torch.mul(). Berikut adalah contoh penggunaan:

Menggunakan operator *:
multiplied_tensor = tensor * 10
Menggunakan fungsi torch.mul():
multiplied_tensor = torch.mul(tensor, 10)
Kode yang benar untuk mengalikan setiap elemen tensor dengan 10 menggunakan fungsi PyTorch adalah menggunakan operator * atau fungsi torch.mul().

In [29]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

Kode tersebut mencoba menunjukkan bahwa tensor asli (sebelum operasi perkalian atau pengurangan) tetap tidak berubah meskipun telah dilakukan operasi matematika pada tensor tersebut. Berikut adalah penjelasan singkat:

tensor: Baris ini adalah untuk menampilkan nilai tensor. Karena tidak ada operasi perubahan yang dilakukan pada tensor setelah operasi perkalian dan pengurangan, nilai tensor yang ditampilkan adalah nilai asli tensor sebelum operasi tersebut.
Contoh outputnya mungkin akan menunjukkan nilai tensor sebelum dilakukan operasi perubahan:
tensor([1, 2, 3])
Ini menunjukkan bahwa meskipun telah dilakukan operasi perkalian dan pengurangan pada tensor menggunakan variabel baru (yang telah di-assign hasilnya), nilai asli dari tensor tetap tidak berubah. Variabel tensor masih berisi nilai [1, 2, 3], yang merupakan nilai tensor sebelum operasi perubahan.

However, it's more common to use the operator symbols like `*` instead of `torch.mul()`

Kode tersebut mencoba menunjukkan bahwa tensor asli (sebelum operasi perkalian atau pengurangan) tetap tidak berubah meskipun telah dilakukan operasi matematika pada tensor tersebut. Berikut adalah penjelasan singkat:

tensor: Baris ini adalah untuk menampilkan nilai tensor. Karena tidak ada operasi perubahan yang dilakukan pada tensor setelah operasi perkalian dan pengurangan, nilai tensor yang ditampilkan adalah nilai asli tensor sebelum operasi tersebut.
Contoh outputnya mungkin akan menunjukkan nilai tensor sebelum dilakukan operasi perubahan:

scss
Copy code
tensor([1, 2, 3])
Ini menunjukkan bahwa meskipun telah dilakukan operasi perkalian dan pengurangan pada tensor menggunakan variabel baru (yang telah di-assign hasilnya), nilai asli dari tensor tetap tidak berubah. Variabel tensor masih berisi nilai [1, 2, 3], yang merupakan nilai tensor sebelum operasi perubahan.

In [30]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


Kode tersebut mencoba menunjukkan operasi perkalian pada setiap elemen tensor dengan dirinya sendiri (operasi perkalian bersifat element-wise). Berikut adalah penjelasan singkat:

print(tensor, "*", tensor): Baris ini mencetak atau menampilkan tensor, tanda perkalian *, dan tensor lagi. Tujuannya adalah untuk menunjukkan operasi element-wise multiplication pada setiap elemen tensor dengan dirinya sendiri. Misalnya, untuk tensor [1, 2, 3], hasilnya akan ditampilkan sebagai tensor * tensor.

print("Equals:", tensor * tensor): Baris ini mencetak atau menampilkan hasil dari operasi perkalian element-wise tersebut. Hasilnya adalah tensor baru yang elemennya merupakan hasil perkalian element-wise dari tensor awal dengan dirinya sendiri.

Contoh outputnya mungkin akan menunjukkan nilai tensor dan hasil perkalian element-wise:
tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
Ini menunjukkan bahwa setiap elemen pada tensor [1, 2, 3] dikalikan dengan elemen yang sesuai dari tensor [1, 2, 3], menghasilkan tensor baru [1, 4, 9]. Hasil ini diperoleh dengan mengalikan elemen-elemen pada posisi yang sesuai satu sama lain.

### Matrix multiplication (is all you need)

One of the most common operations in machine learning and deep learning algorithms (like neural networks) is [matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

PyTorch implements matrix multiplication functionality in the [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html) method.

The main two rules for matrix multiplication to remember are:

1. The **inner dimensions** must match:
  * `(3, 2) @ (3, 2)` won't work
  * `(2, 3) @ (3, 2)` will work
  * `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`

> **Note:** "`@`" in Python is the symbol for matrix multiplication.

> **Resource:** You can see all of the rules for matrix multiplication using `torch.matmul()` [in the PyTorch documentation](https://pytorch.org/docs/stable/generated/torch.matmul.html).

Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.



In [31]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

Kode di atas menggunakan PyTorch untuk membuat sebuah tensor dengan nilai [1, 2, 3] dan kemudian mengakses atribut shape dari tensor tersebut. Berikut adalah penjelasan singkat:

import torch: Mengimpor pustaka PyTorch ke dalam program Python.

tensor = torch.tensor([1, 2, 3]): Membuat tensor dengan elemen-elemen [1, 2, 3] menggunakan fungsi torch.tensor().

tensor.shape: Mengakses atribut shape dari tensor. Atribut shape memberikan informasi tentang jumlah dimensi dan ukuran masing-masing dimensi dalam tensor.

Baris terakhir dari kode tersebut adalah untuk mengeksekusi akses ke atribut shape dan menampilkan hasilnya.

Contoh outputnya mungkin akan menunjukkan bentuk (shape) dari tensor:
torch.Size([3])
Ini menunjukkan bahwa tensor memiliki satu dimensi (vektor) dengan panjang 3. Atribut shape menunjukkan jumlah elemen dalam setiap dimensi. Dalam hal ini, satu dimensi dengan panjang 3. Pastikan bahwa variabel tensor telah didefinisikan sebelumnya untuk menjalankan kode ini.

The difference between element-wise multiplication and matrix multiplication is the addition of values.

For our `tensor` variable with values `[1, 2, 3]`:

| Operation | Calculation | Code |
| ----- | ----- | ----- |
| **Element-wise multiplication** | `[1*1, 2*2, 3*3]` = `[1, 4, 9]` | `tensor * tensor` |
| **Matrix multiplication** | `[1*1 + 2*2 + 3*3]` = `[14]` | `tensor.matmul(tensor)` |


In [32]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

Kode di atas mencoba melakukan operasi perkalian matriks secara elemen-wise pada tensor. Berikut adalah penjelasan singkat:

tensor * tensor: Baris ini mencoba melakukan operasi perkalian matriks secara elemen-wise pada tensor. Operasi ini mengalikan setiap elemen pada tensor dengan elemen yang sesuai dari tensor itu sendiri.
Contoh outputnya mungkin akan menunjukkan hasil operasi perkalian elemen-wise:
tensor([1, 4, 9])
Ini menunjukkan bahwa setiap elemen pada tensor [1, 2, 3] dikalikan dengan elemen yang sesuai dari tensor [1, 2, 3], menghasilkan tensor baru [1, 4, 9]. Hasil ini adalah hasil dari operasi perkalian elemen-wise pada vektor (tensor 1D). Operasi perkalian elemen-wise ini dilakukan pada elemen dengan indeks yang sesuai satu sama lain.

In [33]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)


Kode di atas mencoba melakukan operasi perkalian matriks pada tensor menggunakan fungsi torch.matmul(). Berikut adalah penjelasan singkat:

torch.matmul(tensor, tensor): Baris ini menggunakan fungsi torch.matmul() untuk melakukan operasi perkalian matriks pada tensor. Operasi ini menghasilkan hasil perkalian matriks standar, dan aturan dimensi untuk perkalian matriks harus dipenuhi (jumlah kolom matriks pertama harus sama dengan jumlah baris matriks kedua).
Contoh outputnya mungkin akan menunjukkan hasil perkalian matriks:
tensor(14)
Ini menunjukkan bahwa hasil perkalian matriks dari tensor [1, 2, 3] dengan tensor [1, 2, 3] adalah skalar 14. Hasil ini adalah hasil dari perkalian matriks standar yang mengikuti aturan perkalian matriks. Pastikan bahwa variabel tensor telah didefinisikan sebelumnya untuk menjalankan kode ini.

In [34]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

Kode di atas mencoba melakukan operasi perkalian matriks pada tensor menggunakan operator @. Meskipun operator ini bisa digunakan untuk operasi perkalian matriks, disarankan untuk menggunakan fungsi torch.matmul() untuk kejelasan dan konsistensi. Berikut adalah penjelasan singkat:

tensor @ tensor: Baris ini menggunakan operator @ untuk melakukan operasi perkalian matriks pada tensor. Operator @ dapat digunakan untuk melakukan perkalian matriks, tetapi tidak disarankan untuk kejelasan kode.
Contoh outputnya mungkin akan menunjukkan hasil perkalian matriks:
tensor(14)
Ini menunjukkan bahwa hasil perkalian matriks dari tensor [1, 2, 3] dengan tensor [1, 2, 3] adalah skalar 14. Hasil ini sama dengan hasil yang diperoleh menggunakan torch.matmul(). Meskipun operator @ dapat digunakan, lebih disarankan untuk menggunakan fungsi torch.matmul() agar kode lebih mudah dibaca dan konsisten. Pastikan bahwa variabel tensor telah didefinisikan sebelumnya untuk menjalankan kode ini.

You can do matrix multiplication by hand but it's not recommended.

The in-built `torch.matmul()` method is faster.

In [35]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.44 ms, sys: 0 ns, total: 1.44 ms
Wall time: 1.39 ms


tensor(14)

Kode tersebut mencoba melakukan perkalian matriks secara manual, menghindari penggunaan operasi matriks bawaan PyTorch, dan mengukur waktu yang dibutuhkan untuk operasi tersebut menggunakan cell magic %%time. Berikut adalah penjelasan singkat:

%%time: Cell magic command ini digunakan untuk mengukur waktu eksekusi seluruh sel kode di sel yang sama. Dengan menggunakan %%time, kita dapat melihat berapa lama waktu yang dibutuhkan untuk mengeksekusi seluruh kode di sel tersebut.

Baris berikutnya melakukan perkalian matriks secara manual dengan menggunakan loop for:
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
Kode ini mengiterasi melalui elemen-elemen tensor dan melakukan operasi perkalian matriks secara manual. Setiap elemen dari tensor dikalikan dengan dirinya sendiri, dan hasilnya diakumulasi dalam variabel value.

value: Baris ini mengembalikan atau menampilkan hasil dari operasi perkalian matriks yang dilakukan secara manual.

Contoh outputnya mungkin akan menunjukkan hasil dari operasi perkalian matriks secara manual dan waktu yang dibutuhkan untuk eksekusi:
tensor(14)
CPU times: user 136 µs, sys: 45 µs, total: 181 µs
Wall time: 191 µs
Hasil dari operasi perkalian matriks secara manual adalah skalar 14. Waktu eksekusi ditampilkan di bawahnya, memberikan informasi tentang waktu yang dibutuhkan untuk mengeksekusi seluruh sel tersebut. Perlu diingat bahwa cara ini untuk melakukan perkalian matriks tidak efisien dan kurang disarankan untuk ukuran matriks yang besar karena penggunaan loop for dapat menjadi komputasi yang mahal secara komputasional. Sebaiknya, gunakan fungsi-fungsi matriks bawaan PyTorch seperti torch.matmul() untuk operasi matriks yang lebih efisien.

In [36]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 75 µs, sys: 0 ns, total: 75 µs
Wall time: 78.9 µs


tensor(14)

Kode tersebut menggunakan cell magic %%time untuk mengukur waktu yang dibutuhkan untuk menjalankan operasi perkalian matriks menggunakan fungsi PyTorch torch.matmul(). Berikut adalah penjelasan singkat:

%%time: Cell magic command ini digunakan untuk mengukur waktu eksekusi seluruh sel kode di sel yang sama. Dengan menggunakan %%time, kita dapat melihat berapa lama waktu yang dibutuhkan untuk mengeksekusi seluruh kode di sel tersebut.

torch.matmul(tensor, tensor): Baris ini menggunakan fungsi torch.matmul() untuk melakukan operasi perkalian matriks pada tensor. Operasi ini dilakukan dengan efisien menggunakan implementasi PyTorch.

Contoh outputnya mungkin akan menunjukkan hasil dari operasi perkalian matriks dan waktu yang dibutuhkan untuk eksekusinya:
tensor(14)
CPU times: user 1.35 ms, sys: 36 µs, total: 1.39 ms
Wall time: 1.2 ms
Hasil dari operasi perkalian matriks menggunakan PyTorch adalah skalar 14. Waktu eksekusi ditampilkan di bawahnya, memberikan informasi tentang waktu yang dibutuhkan untuk mengeksekusi seluruh sel tersebut. Perlu diingat bahwa menggunakan fungsi-fungsi matriks bawaan PyTorch seperti torch.matmul() lebih disarankan untuk operasi matriks, karena dapat memberikan kinerja yang lebih baik dan lebih efisien dibandingkan dengan implementasi manual menggunakan loop for.

## One of the most common errors in deep learning (shape errors)

Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [39]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

# Transpose tensor_B to make the matrix multiplication valid
tensor_B_transposed = torch.transpose(tensor_B, 0, 1)

result = torch.matmul(tensor_A, tensor_B_transposed)

print(result)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)
kode diatas saat akan di run terjadi error, error ini muncul karena ketidakcocokan bentuk (shape) tensor yang dioperasikan oleh fungsi torch.matmul. Untuk mengatasi error ini, kita perlu mengubah bentuk salah satu tensor sehingga memenuhi persyaratan perkalian matriks. Dengan melakukan transposisi tensor_B menggunakan torch.transpose(tensor_B, 0, 1), kita mengubah bentuk tensor_B dari (3x2) menjadi (2x3), sehingga dapat dioperasikan dengan tensor_A yang memiliki bentuk (3x2).

Kode tersebut melakukan perkalian matriks antara dua tensor PyTorch (tensor_A dan tensor_B) dan kemudian mencetak hasilnya. Berikut adalah penjelasan singkat:

tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32): Membuat tensor tensor_A dengan nilai [[1, 2], [3, 4], [5, 6]] dan tipe data float32.

tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]], dtype=torch.float32): Membuat tensor tensor_B dengan nilai [[7, 10], [8, 11], [9, 12]] dan tipe data float32.

tensor_B_transposed = torch.transpose(tensor_B, 0, 1): Melakukan operasi transpose pada tensor_B. Ini diperlukan karena bentuk (shape) tensor_A adalah (3, 2), dan bentuk tensor_B adalah (3, 2). Agar dapat melakukan perkalian matriks, jumlah kolom matriks pertama harus sama dengan jumlah baris matriks kedua. Dengan mengubah bentuk tensor_B menjadi (2, 3), kita memastikan bahwa operasi perkalian matriks dapat dilakukan.

result = torch.matmul(tensor_A, tensor_B_transposed): Melakukan operasi perkalian matriks antara tensor_A dan tensor_B_transposed. Hasilnya disimpan dalam variabel result.

print(result): Mencetak hasil perkalian matriks.

Contoh outputnya mungkin akan menunjukkan hasil perkalian matriks:
tensor([[ 27.,  31.,  35.],
        [ 61.,  71.,  81.],
        [ 95., 111., 127.]])
Ini menunjukkan hasil perkalian matriks dari tensor_A dan tensor_B_transposed. Setiap elemen dari hasil matriks adalah hasil perkalian dot produk dari baris tensor_A dengan kolom tensor_B_transposed. Pastikan bahwa variabel tensor_A dan tensor_B telah didefinisikan sebelumnya untuk menjalankan kode ini.

We can make matrix multiplication work between `tensor_A` and `tensor_B` by making their inner dimensions match.

One of the ways to do this is with a **transpose** (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:
* `torch.transpose(input, dim0, dim1)` - where `input` is the desired tensor to transpose and `dim0` and `dim1` are the dimensions to be swapped.
* `tensor.T` - where `tensor` is the desired tensor to transpose.

Let's try the latter.

In [40]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


Kode di atas mencetak atau menampilkan nilai dari dua tensor PyTorch, yaitu tensor_A dan tensor_B. Berikut adalah penjelasan singkat:

print(tensor_A): Baris ini mencetak atau menampilkan nilai dari tensor tensor_A. Variabel tensor_A adalah sebuah matriks dengan nilai [[1, 2], [3, 4], [5, 6]].

print(tensor_B): Baris ini mencetak atau menampilkan nilai dari tensor tensor_B. Variabel tensor_B adalah sebuah matriks dengan nilai [[7, 10], [8, 11], [9, 12]].

Contoh outputnya mungkin akan menunjukkan nilai dari kedua tensor:
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])
Ini menampilkan nilai dari tensor_A dan tensor_B secara berurutan. Setiap tensor memiliki bentuk (shape) dan nilai matriks yang sesuai. Pastikan bahwa variabel tensor_A dan tensor_B telah didefinisikan sebelumnya untuk menjalankan kode ini.

In [41]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


Kode di atas mencetak atau menampilkan nilai dari dua tensor PyTorch, yaitu tensor_A dan transpose dari tensor_B (tensor_B.T). Berikut adalah penjelasan singkat:

print(tensor_A): Baris ini mencetak atau menampilkan nilai dari tensor tensor_A. Variabel tensor_A adalah sebuah matriks dengan nilai [[1, 2], [3, 4], [5, 6]].

print(tensor_B.T): Baris ini mencetak atau menampilkan nilai dari transpose tensor tensor_B. Operasi transpose dilakukan dengan menukar baris menjadi kolom dan sebaliknya. Dengan kata lain, setiap elemen di posisi (i, j) dalam tensor menjadi elemen di posisi (j, i) dalam tensor transpose. Variabel tensor_B.T adalah matriks transpose dari tensor_B.

Contoh outputnya mungkin akan menunjukkan nilai dari tensor_A dan transpose dari tensor_B:
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
Ini menampilkan nilai dari tensor_A dan matriks transpose dari tensor_B. Perhatikan bahwa elemen-elemen di tensor transpose telah ditukar antara baris dan kolom. Pastikan bahwa variabel tensor_A dan tensor_B telah didefinisikan sebelumnya untuk menjalankan kode ini.

In [42]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


Kode di atas mencoba menjelaskan mengapa operasi perkalian matriks (torch.matmul()) bekerja ketika tensor_B di-transpose (tensor_B.T). Berikut adalah penjelasan singkat:

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n"): Baris ini mencetak atau menampilkan bentuk (shape) asli dari tensor_A dan tensor_B.

print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n"): Baris ini mencetak atau menampilkan bentuk (shape) dari tensor_A (tidak berubah) dan bentuk dari transpose tensor_B (tensor_B.T).

print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n"): Baris ini mencetak atau menampilkan pesan yang menjelaskan bahwa operasi perkalian matriks dapat dilakukan karena dimensi dalam ("inner dimensions") tensor sesuai. Dalam konteks ini, bentuk (shape) tensor_A adalah (3, 2), dan bentuk transpose dari tensor_B (tensor_B.T) adalah (2, 3). Inner dimensions yang sesuai adalah 2 dan 2.

output = torch.matmul(tensor_A, tensor_B.T): Baris ini melakukan operasi perkalian matriks antara tensor_A dan transpose tensor_B (tensor_B.T). Hasilnya disimpan dalam variabel output.

print(output): Baris ini mencetak atau menampilkan hasil dari operasi perkalian matriks.

print(f"\nOutput shape: {output.shape}"): Baris ini mencetak atau menampilkan bentuk (shape) dari hasil (output) operasi perkalian matriks.

Contoh outputnya mungkin akan menunjukkan bentuk (shape) dan hasil dari operasi perkalian matriks:
Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  31.,  35.],
        [ 61.,  71.,  81.],
        [ 95., 111., 127.]])

Output shape: torch.Size([3, 3])
Ini memberikan pemahaman tentang bagaimana bentuk tensor memengaruhi operasi perkalian matriks dan mengapa transposisi tensor B diperlukan untuk membuat operasi ini valid. Pastikan bahwa variabel tensor_A dan tensor_B telah didefinisikan sebelumnya untuk menjalankan kode ini.

You can also use [`torch.mm()`](https://pytorch.org/docs/stable/generated/torch.mm.html) which is a short for `torch.matmul()`.

In [43]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Kode di atas menggunakan fungsi torch.mm() untuk melakukan operasi perkalian matriks antara tensor_A dan transpose dari tensor_B (tensor_B.T). Fungsi torch.mm() merupakan pintasan (shortcut) untuk operasi perkalian matriks pada PyTorch. Berikut adalah penjelasan singkat:

torch.mm(tensor_A, tensor_B.T): Baris ini menggunakan fungsi torch.mm() untuk melakukan operasi perkalian matriks antara tensor_A (matriks 3x2) dan transpose dari tensor_B (tensor_B.T, matriks 2x3). Hasilnya adalah matriks berukuran 3x3.
Contoh outputnya mungkin akan menunjukkan hasil dari operasi perkalian matriks:
tensor([[ 27.,  31.,  35.],
        [ 61.,  71.,  81.],
        [ 95., 111., 127.]])
Ini memberikan hasil yang sama seperti menggunakan torch.matmul(), tetapi dengan menggunakan fungsi singkat torch.mm(). Fungsi ini dapat digunakan untuk melakukan operasi perkalian matriks pada dua tensor berukuran 2D. Pastikan bahwa variabel tensor_A dan tensor_B telah didefinisikan sebelumnya untuk menjalankan kode ini.

Without the transpose, the rules of matrix mulitplication aren't fulfilled and we get an error like above.

How about a visual?

![visual demo of matrix multiplication](https://github.com/mrdbourke/pytorch-deep-learning/raw/main/images/00-matrix-multiply-crop.gif)

You can create your own matrix multiplication visuals like this at http://matrixmultiplication.xyz/.

> **Note:** A matrix multiplication like this is also referred to as the [**dot product**](https://www.mathsisfun.com/algebra/vectors-dot-product.html) of two matrices.



Neural networks are full of matrix multiplications and dot products.

The [`torch.nn.Linear()`](https://pytorch.org/docs/1.9.1/generated/torch.nn.Linear.html) module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input `x` and a weights matrix `A`.

$$
y = x\cdot{A^T} + b
$$

Where:
* `x` is the input to the layer (deep learning is a stack of layers like `torch.nn.Linear()` and others on top of each other).
* `A` is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "`T`", that's because the weights matrix gets transposed).
  * **Note:** You might also often see `W` or another letter like `X` used to showcase the weights matrix.
* `b` is the bias term used to slightly offset the weights and inputs.
* `y` is the output (a manipulation of the input in the hopes to discover patterns in it).

This is a linear function (you may have seen something like $y = mx+b$ in high school or elsewhere), and can be used to draw a straight line!

Let's play around with a linear layer.

Try changing the values of `in_features` and `out_features` below and see what happens.

Do you notice anything to do with the shapes?

In [44]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


Kode di atas menciptakan dan menggunakan modul linear (torch.nn.Linear) dengan PyTorch untuk melakukan operasi linier pada tensor tensor_A. Berikut adalah penjelasan singkat:

torch.manual_seed(42): Baris ini mengatur seed untuk generator bilangan acak PyTorch. Ini dilakukan untuk membuat hasil yang dihasilkan secara acak dapat direproduksi pada eksekusi yang berulang, sehingga hasil eksperimen dapat diulang dengan seed yang sama.

linear = torch.nn.Linear(in_features=2, out_features=6): Baris ini membuat objek linear yang merupakan lapisan linier (linear layer) dengan dua parameter: in_features adalah jumlah fitur input, dan out_features adalah jumlah fitur output. Dalam hal ini, layer linear ini mengubah input 2 dimensi menjadi output 6 dimensi.

x = tensor_A: Baris ini mendefinisikan tensor x sebagai tensor input, yang diambil dari tensor_A.

output = linear(x): Baris ini menggunakan layer linear (linear) untuk melakukan transformasi linier pada tensor input x dan menyimpan hasilnya di dalam variabel output.

print(f"Input shape: {x.shape}\n"): Baris ini mencetak atau menampilkan bentuk (shape) dari tensor input x.

print(f"Output:\n{output}\n\nOutput shape: {output.shape}"): Baris ini mencetak atau menampilkan hasil dari operasi linier (output) dan bentuk (shape) dari hasil tersebut.

Contoh outputnya mungkin akan menunjukkan bentuk dan hasil dari operasi linier:
Input shape: torch.Size([3, 2])

Output:
tensor([[ 0.8232,  1.8743, -0.0680, -0.4239,  0.2031, -1.0507],
        [ 1.7726,  3.5587, -0.3848, -1.0326,  0.4565, -2.2329],
        [ 2.7220,  5.2430, -0.7017, -1.6413,  0.7099, -3.4151]],
       grad_fn=<AddmmBackward>)

Output shape: torch.Size([3, 6])
Ini menunjukkan bentuk dan hasil dari operasi linier pada tensor input x. Output memiliki bentuk (shape) [3, 6], sesuai dengan jumlah fitur output yang ditentukan pada layer linear (out_features=6). Perhatikan bahwa gradient function (grad_fn) juga dicetak, menunjukkan bahwa tensor output memiliki ketergantungan terhadap tensor input dan dapat digunakan untuk perhitungan gradien dalam proses pelatihan model.

> **Question:** What happens if you change `in_features` from 2 to 3 above? Does it error? How could you change the shape of the input (`x`) to accomodate to the error? Hint: what did we have to do to `tensor_B` above?

If you've never done it before, matrix multiplication can be a confusing topic at first.

But after you've played around with it a few times and even cracked open a few neural networks, you'll notice it's everywhere.

Remember, matrix multiplication is all you need.

![matrix multiplication is all you need](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00_matrix_multiplication_is_all_you_need.jpeg)

*When you start digging into neural network layers and building your own, you'll find matrix multiplications everywhere. **Source:** https://marksaroufim.substack.com/p/working-class-deep-learner*

### Finding the min, max, mean, sum, etc (aggregation)

Now we've seen a few ways to manipulate tensors, let's run through a few ways to aggregate them (go from more values to less values).

First we'll create a tensor and then find the max, min, mean and sum of it.





In [45]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Kode di atas menciptakan sebuah tensor menggunakan fungsi torch.arange(). Berikut adalah penjelasan singkat:

x = torch.arange(0, 100, 10): Baris ini membuat tensor x dengan menggunakan fungsi torch.arange(). Fungsi ini menghasilkan urutan nilai berdasarkan parameter yang diberikan. Dalam hal ini:

start=0: Nilai awal urutan.
end=100: Nilai akhir urutan (tidak termasuk).
step=10: Selisih antara dua nilai berturut-turut dalam urutan.
Jadi, tensor x akan berisi nilai dari 0 hingga 90 (tidak termasuk 100) dengan selisih 10.

Contoh outputnya mungkin akan menunjukkan nilai dari tensor x:
tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Ini menunjukkan tensor x dengan nilai-nilai yang dibentuk oleh fungsi torch.arange(). Tensor ini merupakan tensor satu dimensi (vektor) dengan 10 elemen.

Now let's perform some aggregation.

In [46]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


Kode di atas mencetak nilai minimum, maksimum, rata-rata, dan jumlah dari tensor x. Berikut adalah penjelasan singkat:

print(f"Minimum: {x.min()}"): Baris ini mencetak nilai minimum dari tensor x menggunakan metode min().

print(f"Maximum: {x.max()}"): Baris ini mencetak nilai maksimum dari tensor x menggunakan metode max().

print(f"Mean: {x.type(torch.float32).mean()}"): Baris ini mencetak nilai rata-rata dari tensor x. Sebelum melakukan operasi rata-rata, tensor dikonversi ke tipe data float32 menggunakan type(torch.float32) untuk menghindari error karena PyTorch mengharapkan tensor bertipe float untuk operasi rata-rata.

print(f"Sum: {x.sum()}"): Baris ini mencetak jumlah dari semua elemen dalam tensor x menggunakan metode sum().

Contoh outputnya mungkin akan menunjukkan nilai statistik dari tensor x:
Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450
Perhatikan bahwa operasi rata-rata menggunakan .mean() membutuhkan tensor bertipe data float, sehingga perlu melakukan konversi tipe data sebelumnya. Jika mengaktifkan baris yang di-comment (# print(f"Mean: {x.mean()}")), akan muncul error karena PyTorch tidak dapat menghitung rata-rata dari tensor dengan tipe data integer secara langsung.

> **Note:** You may find some methods such as `torch.mean()` require tensors to be in `torch.float32` (the most common) or another specific datatype, otherwise the operation will fail.

You can also do the same as above with `torch` methods.

In [47]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

Kode di atas menggunakan beberapa fungsi PyTorch untuk menghitung statistik dari tensor x, termasuk nilai maksimum, minimum, rata-rata, dan jumlah elemen. Berikut adalah penjelasan singkat:

torch.max(x): Fungsi ini mengembalikan nilai maksimum dari tensor x. Dalam hal ini, mengembalikan sebuah tensor dengan nilai maksimum dan indeks elemen maksimum.

torch.min(x): Fungsi ini mengembalikan nilai minimum dari tensor x. Dalam hal ini, mengembalikan sebuah tensor dengan nilai minimum dan indeks elemen minimum.

torch.mean(x.type(torch.float32)): Fungsi ini menghitung rata-rata dari tensor x. Sebelum menghitung rata-rata, tensor dikonversi menjadi tipe data float32 untuk menghindari error, karena operasi rata-rata membutuhkan tensor dengan tipe data float.

torch.sum(x): Fungsi ini menghitung jumlah dari semua elemen dalam tensor x.

Contoh penggunaan masing-masing fungsi dalam sebuah ekspresi:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)
Contoh outputnya mungkin akan menunjukkan nilai maksimum, minimum, rata-rata, dan jumlah dari tensor x:
(tensor(90), tensor(0), tensor(45.), tensor(450))
Ini menunjukkan bahwa nilai maksimum dalam tensor x adalah 90, nilai minimum adalah 0, rata-rata adalah 45, dan jumlah seluruh elemennya adalah 450.

### Positional min/max

You can also find the index of a tensor where the max or minimum occurs with [`torch.argmax()`](https://pytorch.org/docs/stable/generated/torch.argmax.html) and [`torch.argmin()`](https://pytorch.org/docs/stable/generated/torch.argmin.html) respectively.

This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the [softmax activation function](https://pytorch.org/docs/stable/generated/torch.nn.Softmax.html)).

In [48]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


Kode di atas menciptakan sebuah tensor menggunakan fungsi torch.arange() dan kemudian mengidentifikasi indeks dari nilai maksimum dan minimum dalam tensor tersebut. Berikut adalah penjelasan singkat:

tensor = torch.arange(10, 100, 10): Baris ini membuat tensor tensor dengan menggunakan fungsi torch.arange(). Fungsi ini menghasilkan urutan nilai berdasarkan parameter yang diberikan. Dalam hal ini, tensor tensor akan berisi nilai dari 10 hingga 90 (tidak termasuk 100) dengan selisih 10.

print(f"Tensor: {tensor}"): Baris ini mencetak nilai dari tensor tensor.

print(f"Index where max value occurs: {tensor.argmax()}"): Baris ini mencetak indeks dari nilai maksimum dalam tensor tensor menggunakan metode argmax(). Fungsi ini mengembalikan indeks dari elemen dengan nilai maksimum.

print(f"Index where min value occurs: {tensor.argmin()}"): Baris ini mencetak indeks dari nilai minimum dalam tensor tensor menggunakan metode argmin(). Fungsi ini mengembalikan indeks dari elemen dengan nilai minimum.

Contoh outputnya mungkin akan menunjukkan tensor dan indeks dari nilai maksimum dan minimum:
Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0
Ini menunjukkan bahwa nilai maksimum dalam tensor tensor adalah 90, dan nilai minimum adalah 10. Indeks 8 menunjukkan posisi di mana nilai maksimum (90) ditemukan, dan indeks 0 menunjukkan posisi di mana nilai minimum (10) ditemukan dalam tensor.

### Change tensor datatype

As mentioned, a common issue with deep learning operations is having your tensors in different datatypes.

If one tensor is in `torch.float64` and another is in `torch.float32`, you might run into some errors.

But there's a fix.

You can change the datatypes of tensors using [`torch.Tensor.type(dtype=None)`](https://pytorch.org/docs/stable/generated/torch.Tensor.type.html) where the `dtype` parameter is the datatype you'd like to use.

First we'll create a tensor and check it's datatype (the default is `torch.float32`).

In [49]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

Kode di atas menciptakan sebuah tensor menggunakan fungsi torch.arange() dengan menggunakan parameter untuk nilai start, end, dan step yang bertipe float. Setelah itu, kode tersebut mengambil dan mencetak tipe data (dtype) dari tensor tersebut. Berikut adalah penjelasan singkat:

tensor = torch.arange(10., 100., 10.): Baris ini membuat tensor tensor dengan menggunakan fungsi torch.arange(). Dalam hal ini, parameter start=10., end=100., dan step=10. digunakan untuk menghasilkan urutan nilai float dari 10 hingga 90 (tidak termasuk 100) dengan selisih 10.

tensor.dtype: Baris ini mengakses properti dtype dari tensor tensor. Properti ini memberikan informasi tentang tipe data (data type) dari tensor.

Contoh outputnya mungkin akan menunjukkan tipe data dari tensor tensor:
torch.float32
Ini menunjukkan bahwa tensor tensor memiliki tipe data float32. Penggunaan tanda desimal (.) pada parameter fungsi torch.arange() menyebabkan tensor yang dihasilkan memiliki tipe data float.

Now we'll create another tensor the same as before but change its datatype to `torch.float16`.



In [50]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

Kode di atas menciptakan sebuah tensor baru dengan tipe data float16 (torch.float16) yang diperoleh dari tensor sebelumnya (tensor). Berikut adalah penjelasan singkat:

tensor_float16 = tensor.type(torch.float16): Baris ini membuat tensor baru, tensor_float16, dengan mengonversi tipe data tensor sebelumnya (tensor) menjadi float16 menggunakan metode .type(torch.float16). Metode ini memungkinkan kita untuk mengubah tipe data tensor.

tensor_float16: Baris ini mencetak atau menampilkan tensor yang baru dibuat dengan tipe data float16.

Contoh outputnya mungkin akan menunjukkan nilai dari tensor baru dengan tipe data float16:
tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)
Ini menunjukkan bahwa tensor tensor_float16 memiliki nilai yang sama seperti tensor sebelumnya (tensor), tetapi dengan tipe data yang diubah menjadi float16. Perhatikan bahwa float16 memiliki presisi lebih rendah dibandingkan dengan float32 atau float64, sehingga dapat menghemat ruang memori, tetapi dengan tingkat presisi yang lebih rendah.

And we can do something similar to make a `torch.int8` tensor.

In [51]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

> **Note:** Different datatypes can be confusing to begin with. But think of it like this, the lower the number (e.g. 32, 16, 8), the less precise a computer stores the value. And with a lower amount of storage, this generally results in faster computation and a smaller overall model. Mobile-based neural networks often operate with 8-bit integers, smaller and faster to run but less accurate than their float32 counterparts. For more on this, I'd read up about [precision in computing](https://en.wikipedia.org/wiki/Precision_(computer_science)).

> **Exercise:** So far we've covered a fair few tensor methods but there's a bunch more in the [`torch.Tensor` documentation](https://pytorch.org/docs/stable/tensors.html), I'd recommend spending 10-minutes scrolling through and looking into any that catch your eye. Click on them and then write them out in code yourself to see what happens.

### Reshaping, stacking, squeezing and unsqueezing

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. |
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. |

Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors.

Let's try them out.

First, we'll create a tensor.

In [52]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

Kode di atas menciptakan sebuah tensor baru dengan tipe data int8 (torch.int8) yang diperoleh dari tensor sebelumnya (tensor). Berikut adalah penjelasan singkat:

tensor_int8 = tensor.type(torch.int8): Baris ini membuat tensor baru, tensor_int8, dengan mengonversi tipe data tensor sebelumnya (tensor) menjadi int8 menggunakan metode .type(torch.int8). Metode ini memungkinkan kita untuk mengubah tipe data tensor.

tensor_int8: Baris ini mencetak atau menampilkan tensor yang baru dibuat dengan tipe data int8.

Contoh outputnya mungkin akan menunjukkan nilai dari tensor baru dengan tipe data int8:
tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)
Ini menunjukkan bahwa tensor tensor_int8 memiliki nilai yang sama seperti tensor sebelumnya (tensor), tetapi dengan tipe data yang diubah menjadi int8. Perlu diingat bahwa int8 memiliki rentang nilai yang terbatas (dari -128 hingga 127) dan dapat membatasi representasi nilai jika nilai di luar rentang tersebut. Sebagai contoh, nilai-nilai di luar rentang tersebut akan diatur ke nilai maksimum atau minimum yang valid.

Now let's add an extra dimension with `torch.reshape()`.

In [53]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Kode di atas menciptakan sebuah tensor menggunakan fungsi torch.arange() dengan parameter start=1. dan end=8.. Setelah itu, kode tersebut mencetak nilai dari tensor tersebut (x) serta bentuknya (shape). Berikut adalah penjelasan singkat:

import torch: Import library PyTorch untuk digunakan dalam kode.

x = torch.arange(1., 8.): Baris ini membuat tensor x dengan menggunakan fungsi torch.arange(). Dalam hal ini, parameter start=1. dan end=8. digunakan untuk menghasilkan urutan nilai float dari 1 hingga 7 (tidak termasuk 8).

x: Baris ini mencetak atau menampilkan nilai dari tensor x.

x.shape: Baris ini mengakses properti shape dari tensor x. Properti ini memberikan informasi tentang bentuk (shape) dari tensor.

Contoh outputnya mungkin akan menunjukkan nilai dan bentuk dari tensor x:
(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))
Ini menunjukkan bahwa tensor x memiliki nilai dari 1 hingga 7 dan bentuknya adalah [7], menunjukkan bahwa tensor ini adalah tensor satu dimensi (vektor) dengan panjang 7 elemen.

We can also change the view with `torch.view()`.

In [54]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Kode di atas menggunakan metode view() pada tensor x untuk mengubah tampilan atau bentuk tensor tersebut. Berikut adalah penjelasan singkat:

z = x.view(1, 7): Baris ini menggunakan metode view() untuk membuat tensor baru z dengan bentuk (shape) baru [1, 7]. Metode ini memungkinkan kita untuk mengubah tampilan tensor tanpa mengubah data yang sebenarnya. Dalam hal ini, z menjadi tensor dengan satu baris dan tujuh kolom.

z: Baris ini mencetak atau menampilkan nilai dari tensor yang baru dibuat, yaitu z.

z.shape: Baris ini mengakses properti shape dari tensor z. Properti ini memberikan informasi tentang bentuk (shape) dari tensor.

Contoh outputnya mungkin akan menunjukkan nilai dan bentuk dari tensor z:
(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))
Ini menunjukkan bahwa tensor z memiliki nilai yang sama dengan tensor x, tetapi bentuknya telah diubah menjadi [1, 7], menunjukkan bahwa sekarang ini adalah tensor dua dimensi dengan satu baris dan tujuh kolom. Konsep ini disebut sebagai "view" atau "reshape", di mana kita mempertahankan data yang sama tetapi mengubah cara kita melihat atau mengakses tensor tersebut.

Remember though, changing the view of a tensor with `torch.view()` really only creates a new view of the *same* tensor.

So changing the view changes the original tensor too.

In [55]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

Kode di atas menunjukkan bahwa ketika kita melakukan perubahan pada tensor z, perubahan tersebut juga tercermin pada tensor x, dan sebaliknya. Hal ini terjadi karena tensor z menggunakan tampilan yang sama dengan tensor x. Berikut adalah penjelasan singkat:

z[:, 0] = 5: Baris ini mengganti nilai elemen pertama (kolom 0) dari tensor z dengan nilai 5. Notasi [:, 0] mengindikasikan bahwa kita mengganti seluruh baris untuk kolom dengan indeks 0.

z: Baris ini mencetak atau menampilkan nilai dari tensor z setelah perubahan.

x: Baris ini mencetak atau menampilkan nilai dari tensor x.

Contoh outputnya mungkin akan menunjukkan nilai setelah perubahan pada tensor z dan x:
(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))
Ini menunjukkan bahwa ketika kita mengubah nilai elemen pertama dari tensor z menjadi 5, nilai yang sama juga muncul pada tensor x. Hal ini terjadi karena keduanya menggunakan tampilan yang sama terhadap data yang sama. Jadi, perubahan pada satu tensor juga memengaruhi tensor yang lain.

If we wanted to stack our new tensor on top of itself five times, we could do so with `torch.stack()`.

In [56]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

Kode di atas menggunakan fungsi torch.stack() untuk menggabungkan beberapa tensor ke dalam satu tensor yang baru dengan menumpuknya secara vertikal (dalam dimensi tertentu). Berikut adalah penjelasan singkat:

x_stacked = torch.stack([x, x, x, x], dim=0): Baris ini menggunakan fungsi torch.stack() untuk membuat tensor baru x_stacked dengan menumpuk tensor x sebanyak empat kali secara vertikal. Parameter dim=0 menunjukkan bahwa penumpukan dilakukan dalam dimensi pertama (baris).

Jika dim diubah menjadi dim=1, penumpukan akan dilakukan dalam dimensi kedua (kolom), sehingga tensor akan menjadi horizontal.
x_stacked: Baris ini mencetak atau menampilkan nilai dari tensor x_stacked yang baru dibuat.

Contoh outputnya mungkin akan menunjukkan nilai dari tensor x_stacked:
tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])
Ini menunjukkan bahwa tensor x_stacked terdiri dari empat salinan tensor x yang ditumpuk secara vertikal dalam dimensi pertama (baris). Setiap baris menunjukkan salinan dari tensor x. Jika parameter dim diubah menjadi dim=1, penumpukan akan dilakukan dalam dimensi kedua (kolom), sehingga tensor akan menjadi horizontal.

How about removing all single dimensions from a tensor?

To do so you can use `torch.squeeze()` (I remember this as *squeezing* the tensor to only have dimensions over 1).

In [57]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


Kode di atas menunjukkan operasi untuk menghilangkan dimensi yang tidak diperlukan dari tensor menggunakan metode squeeze(). Berikut adalah penjelasan singkat:

print(f"Previous tensor: {x_reshaped}"): Baris ini mencetak nilai dari tensor sebelum operasi penghilangan dimensi, yaitu tensor x_reshaped.

print(f"Previous shape: {x_reshaped.shape}"): Baris ini mencetak bentuk (shape) dari tensor sebelum operasi penghilangan dimensi, yaitu bentuk tensor x_reshaped.

x_squeezed = x_reshaped.squeeze(): Baris ini menggunakan metode squeeze() untuk menghasilkan tensor baru x_squeezed dengan menghilangkan dimensi yang memiliki panjang 1. Metode ini secara otomatis menghilangkan dimensi yang tidak diperlukan.

print(f"\nNew tensor: {x_squeezed}"): Baris ini mencetak nilai dari tensor setelah operasi penghilangan dimensi, yaitu tensor x_squeezed.

print(f"New shape: {x_squeezed.shape}"): Baris ini mencetak bentuk (shape) dari tensor setelah operasi penghilangan dimensi, yaitu bentuk tensor x_squeezed.

Contoh outputnya mungkin akan menunjukkan nilai dan bentuk sebelum dan setelah penghilangan dimensi:
Previous tensor: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.]])
Previous shape: torch.Size([7, 1])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])
Ini menunjukkan bahwa tensor x_reshaped sebelumnya memiliki bentuk [7, 1] (tensor kolom), dan setelah operasi squeeze(), dimensi dengan panjang 1 dihilangkan sehingga tensor x_squeezed memiliki bentuk [7] (tensor satu dimensi atau vektor).

And to do the reverse of `torch.squeeze()` you can use `torch.unsqueeze()` to add a dimension value of 1 at a specific index.

In [58]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


Kode di atas menunjukkan operasi untuk menambahkan dimensi tambahan ke dalam tensor menggunakan metode unsqueeze(). Berikut adalah penjelasan singkat:

print(f"Previous tensor: {x_squeezed}"): Baris ini mencetak nilai dari tensor sebelum operasi penambahan dimensi, yaitu tensor x_squeezed.

print(f"Previous shape: {x_squeezed.shape}"): Baris ini mencetak bentuk (shape) dari tensor sebelum operasi penambahan dimensi, yaitu bentuk tensor x_squeezed.

x_unsqueezed = x_squeezed.unsqueeze(dim=0): Baris ini menggunakan metode unsqueeze() untuk menambahkan dimensi tambahan ke dalam tensor x_squeezed. Parameter dim=0 menunjukkan bahwa dimensi baru akan ditambahkan di posisi pertama (sebagai dimensi pertama).

print(f"\nNew tensor: {x_unsqueezed}"): Baris ini mencetak nilai dari tensor setelah operasi penambahan dimensi, yaitu tensor x_unsqueezed.

print(f"New shape: {x_unsqueezed.shape}"): Baris ini mencetak bentuk (shape) dari tensor setelah operasi penambahan dimensi, yaitu bentuk tensor x_unsqueezed.

Contoh outputnya mungkin akan menunjukkan nilai dan bentuk sebelum dan setelah penambahan dimensi:
Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])
Ini menunjukkan bahwa tensor x_squeezed sebelumnya memiliki bentuk [7] (tensor satu dimensi atau vektor), dan setelah operasi unsqueeze(), dimensi baru dengan panjang 1 ditambahkan sehingga tensor x_unsqueezed memiliki bentuk [1, 7] (tensor dengan satu baris dan tujuh kolom).

You can also rearrange the order of axes values with `torch.permute(input, dims)`, where the `input` gets turned into a *view* with new `dims`.

In [59]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


Kode di atas menciptakan sebuah tensor dengan bentuk (shape) tertentu, kemudian menggunakan metode permute() untuk menukar urutan sumbu atau dimensi tensor. Berikut adalah penjelasan singkat:

x_original = torch.rand(size=(224, 224, 3)): Baris ini menciptakan tensor x_original dengan menggunakan fungsi torch.rand() untuk menghasilkan nilai acak dengan bentuk (shape) [224, 224, 3]. Ini bisa diasumsikan sebagai gambar dengan lebar 224 piksel, tinggi 224 piksel, dan 3 saluran warna (RGB).

x_permuted = x_original.permute(2, 0, 1): Baris ini menggunakan metode permute() untuk menukar urutan sumbu atau dimensi tensor. Dalam hal ini, dimensi 0 dipindahkan ke dimensi 1, dimensi 1 dipindahkan ke dimensi 2, dan dimensi 2 dipindahkan ke dimensi 0. Ini sering digunakan dalam konteks pengolahan gambar untuk mengubah urutan sumbu agar sesuai dengan format yang diinginkan.

print(f"Previous shape: {x_original.shape}"): Baris ini mencetak bentuk (shape) dari tensor x_original sebelum operasi pemutaran dimensi.

print(f"New shape: {x_permuted.shape}"): Baris ini mencetak bentuk (shape) dari tensor x_permuted setelah operasi pemutaran dimensi.

Contoh outputnya mungkin akan menunjukkan bentuk sebelum dan setelah pemutaran dimensi:
Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
Ini menunjukkan bahwa tensor x_original memiliki bentuk [224, 224, 3], dan setelah operasi permute(), dimensi atau sumbu dari tensor x_permuted telah diubah menjadi [3, 224, 224]. Ini berguna, misalnya, ketika bekerja dengan model jaringan saraf yang memerlukan format input khusus.

> **Note**: Because permuting returns a *view* (shares the same data as the original), the values in the permuted tensor will be the same as the original tensor and if you change the values in the view, it will change the values of the original.

## Indexing (selecting data from tensors)

Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

To do so, you can use indexing.

If you've ever done indexing on Python lists or NumPy arrays, indexing in PyTorch with tensors is very similar.

In [60]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

Kode di atas membuat sebuah tensor menggunakan fungsi torch.arange() untuk membuat urutan nilai dari 1 hingga 9, dan kemudian menggunakan metode reshape() untuk mengubah bentuk atau dimensi tensor. Berikut adalah penjelasan singkat:

import torch: Baris ini mengimpor library PyTorch untuk digunakan dalam kode.

x = torch.arange(1, 10).reshape(1, 3, 3): Baris ini membuat tensor x dengan menggunakan fungsi torch.arange() untuk menghasilkan urutan nilai dari 1 hingga 9. Selanjutnya, metode reshape(1, 3, 3) digunakan untuk mengubah bentuk tensor menjadi matriks 3x3 dan menambahkan dimensi ekstra di depannya (dimensi pertama menjadi 1). Jadi, bentuk akhirnya adalah [1, 3, 3].

x: Baris ini mencetak atau menampilkan nilai dari tensor x.

x.shape: Baris ini mengakses properti shape dari tensor x, yang memberikan informasi tentang bentuk (shape) dari tensor.

Contoh outputnya mungkin akan menunjukkan nilai dan bentuk dari tensor x:
(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))
Ini menunjukkan bahwa tensor x memiliki nilai dari 1 hingga 9 dan bentuk [1, 3, 3], yang berarti tensor ini adalah tensor tiga dimensi dengan satu salinan matriks 3x3.

Indexing values goes outer dimension -> inner dimension (check out the square brackets).

In [61]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


Kode di atas menggunakan indeksing untuk mengakses elemen dari tensor x. Berikut adalah penjelasan singkat:

print(f"First square bracket:\n{x[0]}"): Baris ini mencetak atau menampilkan hasil indeksing pertama dari tensor x. Dengan menggunakan indeks [0], kita mengakses elemen pertama dari tensor x, yang dalam hal ini adalah seluruh matriks 3x3.

print(f"Second square bracket: {x[0][0]}"): Baris ini mencetak atau menampilkan hasil indeksing kedua dari tensor x. Dengan menggunakan indeks [0][0], kita mengakses elemen pertama dari matriks yang telah diakses pada langkah sebelumnya, sehingga kita mendapatkan baris pertama dari matriks tersebut.

print(f"Third square bracket: {x[0][0][0]}"): Baris ini mencetak atau menampilkan hasil indeksing ketiga dari tensor x. Dengan menggunakan indeks [0][0][0], kita mengakses elemen pertama dari baris pertama dari matriks yang telah diakses pada langkah sebelumnya, sehingga kita mendapatkan elemen pertama dari tensor awal.

Contoh outputnya mungkin akan menunjukkan nilai dari setiap langkah indeksing:
First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1
Ini menunjukkan bahwa melalui langkah-langkah indeksing, kita dapat mengakses elemen-elemen spesifik dari tensor.

You can also use `:` to specify "all values in this dimension" and then use a comma (`,`) to add another dimension.

In [62]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

Kode di atas menggunakan slicing untuk mengakses sebagian dari tensor x. Dalam hal ini, kita ingin mendapatkan semua nilai dari dimensi ke-0 dan indeks ke-0 dari dimensi ke-1. Berikut adalah penjelasan singkat:

x[:, 0]: Baris ini menggunakan slicing untuk mendapatkan sebagian dari tensor x. Slicing dilakukan dengan menggunakan : pada dimensi ke-0, yang berarti kita ingin mengambil semua nilai dari dimensi tersebut. Selanjutnya, menggunakan indeks 0 pada dimensi ke-1, kita ingin mendapatkan nilai pada indeks ke-0 dari setiap array di dalam dimensi ke-1.
Contoh outputnya mungkin akan menunjukkan nilai dari hasil slicing:
tensor([[1, 2, 3]])
Ini menunjukkan bahwa kita mendapatkan baris pertama dari tensor x, yaitu [1, 2, 3], yang sesuai dengan indeks ke-0 dari setiap array di dalam dimensi ke-1.

In [63]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

Kode di atas menggunakan slicing untuk mengakses sebagian dari tensor x. Dalam hal ini, kita ingin mendapatkan semua nilai dari dimensi ke-0 dan ke-1, tetapi hanya indeks ke-1 dari dimensi ke-2. Berikut adalah penjelasan singkat:

x[:, :, 1]: Baris ini menggunakan slicing untuk mendapatkan sebagian dari tensor x.
: pada dimensi ke-0 dan ke-1 berarti kita ingin mengambil semua nilai dari dimensi tersebut.
1 pada dimensi ke-2 berarti kita hanya ingin mengambil nilai pada indeks ke-1 dari setiap array di dalam dimensi ke-2.
Contoh outputnya mungkin akan menunjukkan nilai dari hasil slicing:
tensor([[2],
        [5],
        [8]])
Ini menunjukkan bahwa kita mendapatkan kolom kedua dari setiap matriks di dalam dimensi ke-2, yang sesuai dengan indeks ke-1 dari dimensi tersebut. Sebagai contoh, kita mendapatkan nilai [2, 5, 8] dari kolom kedua.

In [64]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

Kode di atas menggunakan slicing untuk mengakses sebagian dari tensor x. Dalam hal ini, kita ingin mendapatkan semua nilai dari dimensi ke-0, tetapi hanya nilai pada indeks ke-1 dari dimensi ke-1 dan ke-2. Berikut adalah penjelasan singkat:

x[:, 1, 1]: Baris ini menggunakan slicing untuk mendapatkan sebagian dari tensor x.
: pada dimensi ke-0 berarti kita ingin mengambil semua nilai dari dimensi tersebut.
1 pada dimensi ke-1 berarti kita hanya ingin mengambil nilai pada indeks ke-1 dari dimensi tersebut.
1 pada dimensi ke-2 berarti kita hanya ingin mengambil nilai pada indeks ke-1 dari dimensi tersebut.
Contoh outputnya mungkin akan menunjukkan nilai dari hasil slicing:
tensor([5])
Ini menunjukkan bahwa kita mendapatkan nilai pada indeks ke-1 dari dimensi ke-1 dan ke-2, tetapi semua nilai dari dimensi ke-0. Sebagai contoh, kita mendapatkan nilai 5 yang merupakan nilai pada indeks ke-1 dari dimensi ke-1 dan ke-2 pada tensor x.

In [65]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

Kode di atas menggunakan indeksing untuk mengakses sebagian dari tensor x. Dalam hal ini, kita ingin mendapatkan nilai pada indeks ke-0 dari dimensi ke-0 dan ke-1, tetapi semua nilai dari dimensi ke-2. Berikut adalah penjelasan singkat:

x[0, 0, :]: Baris ini menggunakan indeksing untuk mendapatkan sebagian dari tensor x.
0 pada dimensi ke-0 dan ke-1 berarti kita ingin mengambil nilai pada indeks ke-0 dari kedua dimensi tersebut.
: pada dimensi ke-2 berarti kita ingin mengambil semua nilai dari dimensi tersebut.
Contoh outputnya mungkin akan menunjukkan nilai dari hasil indeksing:
tensor([1, 2, 3])
Ini menunjukkan bahwa kita mendapatkan nilai pada indeks ke-0 dari dimensi ke-0 dan ke-1, tetapi semua nilai dari dimensi ke-2. Dalam hal ini, kita mendapatkan nilai [1, 2, 3] yang merupakan nilai pada indeks ke-0 dari dimensi ke-0 dan ke-1 pada tensor x. Juga, perlu dicatat bahwa x[0, 0, :] ekuivalen dengan x[0][0], yaitu cara lain untuk mencapai hasil yang sama.

Indexing can be quite confusing to begin with, especially with larger tensors (I still have to try indexing multiple times to get it right). But with a bit of practice and following the data explorer's motto (***visualize, visualize, visualize***), you'll start to get the hang of it.

## PyTorch tensors & NumPy

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.  

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:
* [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - NumPy array -> PyTorch tensor.
* [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) - PyTorch tensor -> NumPy array.

Let's try them out.

In [66]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Kode di atas mengilustrasikan cara mengonversi array NumPy menjadi tensor PyTorch. Berikut adalah penjelasan singkat:

import torch dan import numpy as np: Baris ini mengimpor library PyTorch dan NumPy untuk digunakan dalam kode.

array = np.arange(1.0, 8.0): Baris ini membuat array NumPy menggunakan fungsi np.arange() untuk menghasilkan urutan nilai dari 1.0 hingga 7.0. Nilai 8.0 tidak termasuk dalam array.

tensor = torch.from_numpy(array): Baris ini menggunakan fungsi torch.from_numpy() untuk mengonversi array NumPy menjadi tensor PyTorch. Tensor yang dihasilkan akan memiliki tipe data yang sesuai dengan tipe data array NumPy.

array: Baris ini mencetak atau menampilkan nilai dari array NumPy.

tensor: Baris ini mencetak atau menampilkan nilai dari tensor PyTorch yang dihasilkan.

Contoh outputnya mungkin akan menunjukkan nilai dari array NumPy dan tensor PyTorch:
(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))
Ini menunjukkan bahwa array NumPy [1., 2., 3., 4., 5., 6., 7.] telah berhasil dikonversi menjadi tensor PyTorch dengan tipe data torch.float64. Konversi ini berguna ketika kita ingin bekerja dengan data dalam format tensor PyTorch dalam konteks penggunaan PyTorch.

> **Note:** By default, NumPy arrays are created with the datatype `float64` and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).
>
> However, many PyTorch calculations default to using `float32`.
>
> So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use `tensor = torch.from_numpy(array).type(torch.float32)`.

Because we reassigned `tensor` above, if you change the tensor, the array stays the same.

In [67]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Kode di atas menunjukkan pengaruh perubahan pada array NumPy terhadap tensor PyTorch yang dihasilkan sebelumnya melalui fungsi torch.from_numpy(). Berikut adalah penjelasan singkat:

array = array + 1: Baris ini menambahkan nilai 1 ke setiap elemen dalam array NumPy. Ini adalah operasi yang dilakukan pada array NumPy.

array: Baris ini mencetak atau menampilkan nilai dari array NumPy setelah dilakukan penambahan.

tensor: Baris ini mencetak atau menampilkan nilai dari tensor PyTorch yang dihasilkan sebelumnya.

Contoh outputnya mungkin akan menunjukkan nilai dari array NumPy dan tensor PyTorch setelah perubahan array:
(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))
Perhatikan bahwa nilai tensor PyTorch tetap tidak berubah meskipun ada perubahan pada array NumPy. Fungsi torch.from_numpy() tidak membuat salinan data, tetapi berbagi memori antara array NumPy dan tensor PyTorch. Oleh karena itu, perubahan pada array NumPy dapat tercermin dalam tensor PyTorch. Jika Anda ingin menghindari perubahan ini, Anda dapat membuat salinan tensor dengan menggunakan tensor.clone() atau torch.tensor(array).

And if you want to go from PyTorch tensor to NumPy array, you can call `tensor.numpy()`.

In [68]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Kode di atas menunjukkan cara mengonversi tensor PyTorch menjadi array NumPy. Berikut adalah penjelasan singkat:

tensor = torch.ones(7): Baris ini membuat tensor PyTorch yang berisi tujuh elemen dengan nilai satu. Tensor ini memiliki tipe data default float32.

numpy_tensor = tensor.numpy(): Baris ini menggunakan metode numpy() untuk mengonversi tensor PyTorch tensor menjadi array NumPy numpy_tensor. Perlu diingat bahwa kedua objek (tensor dan array) akan berbagi memori, yang berarti perubahan pada salah satu dari mereka akan tercermin pada yang lainnya.

tensor: Baris ini mencetak atau menampilkan nilai dari tensor PyTorch.

numpy_tensor: Baris ini mencetak atau menampilkan nilai dari array NumPy yang dihasilkan dari tensor PyTorch.

Contoh outputnya mungkin akan menunjukkan nilai dari tensor PyTorch dan array NumPy:
(tensor([1., 1., 1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))
Ini menunjukkan bahwa tensor PyTorch [1., 1., 1., 1., 1., 1., 1.] telah berhasil dikonversi menjadi array NumPy dengan tipe data float32. Jika terdapat perubahan pada tensor PyTorch, perubahan tersebut juga akan tercermin pada array NumPy karena keduanya berbagi memori.

And the same rule applies as above, if you change the original `tensor`, the new `numpy_tensor` stays the same.

In [69]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Kode di atas menunjukkan pengaruh perubahan pada tensor PyTorch terhadap array NumPy yang dihasilkan sebelumnya melalui fungsi tensor.numpy(). Berikut adalah penjelasan singkat:

tensor = tensor + 1: Baris ini menambahkan nilai 1 ke setiap elemen dalam tensor PyTorch. Ini adalah operasi yang dilakukan pada tensor PyTorch.

tensor: Baris ini mencetak atau menampilkan nilai dari tensor PyTorch setelah dilakukan penambahan.

numpy_tensor: Baris ini mencetak atau menampilkan nilai dari array NumPy yang dihasilkan sebelumnya.

Contoh outputnya mungkin akan menunjukkan nilai dari tensor PyTorch dan array NumPy setelah perubahan tensor:
(tensor([2., 2., 2., 2., 2., 2., 2.]), array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))
Perhatikan bahwa nilai tensor PyTorch berubah setelah penambahan, tetapi nilai array NumPy tetap tidak berubah. Meskipun keduanya berbagi memori, perubahan pada tensor PyTorch tidak tercermin pada array NumPy. Hal ini karena konversi dari tensor PyTorch ke array NumPy menggunakan fungsi numpy() membuat salinan data, sehingga perubahan pada tensor tidak mempengaruhi array yang sudah dihasilkan.

## Reproducibility (trying to take the random out of random)

As you learn more about neural networks and machine learning, you'll start to discover how much randomness plays a part.

Well, pseudorandomness that is. Because after all, as they're designed, a computer is fundamentally deterministic (each step is predictable) so the randomness they create are simulated randomness (though there is debate on this too, but since I'm not a computer scientist, I'll let you find out more yourself).

How does this relate to neural networks and deep learning then?

We've discussed neural networks start with random numbers to describe patterns in data (these numbers are poor descriptions) and try to improve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data.

In short:

``start with random numbers -> tensor operations -> try to make better (again and again and again)``

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?

So you can perform repeatable experiments.

For example, you create an algorithm capable of achieving X performance.

And then your friend tries it out to verify you're not crazy.

How could they do such a thing?

That's where **reproducibility** comes in.

In other words, can you get the same (or very similar) results on your computer running the same code as I get on mine?

Let's see a brief example of reproducibility in PyTorch.

We'll start by creating two random tensors, since they're random, you'd expect them to be different right?

In [70]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Kode di atas menggunakan PyTorch untuk membuat dua tensor acak (random_tensor_A dan random_tensor_B) dan memeriksa apakah keduanya sama dalam hal elemen-elemen mereka. Berikut adalah penjelasan singkat:

import torch: Baris ini mengimpor library PyTorch, memungkinkan penggunaan fungsi-fungsi dan struktur data PyTorch.

random_tensor_A = torch.rand(3, 4): Baris ini membuat tensor acak random_tensor_A dengan bentuk (shape) 3x4 menggunakan fungsi torch.rand(). Tensor ini akan berisi nilai-nilai acak antara 0 dan 1.

random_tensor_B = torch.rand(3, 4): Baris ini membuat tensor acak random_tensor_B dengan bentuk (shape) yang sama seperti random_tensor_A.

print(f"Tensor A:\n{random_tensor_A}\n"): Baris ini mencetak atau menampilkan nilai dari tensor random_tensor_A.

print(f"Tensor B:\n{random_tensor_B}\n"): Baris ini mencetak atau menampilkan nilai dari tensor random_tensor_B.

print(f"Does Tensor A equal Tensor B? (anywhere)"): Baris ini mencetak atau menampilkan pesan pertanyaan.

random_tensor_A == random_tensor_B: Baris ini menggunakan operator perbandingan == untuk memeriksa apakah nilai-nilai elemen dalam random_tensor_A sama dengan nilai-nilai elemen dalam random_tensor_B. Hasilnya adalah tensor boolean yang menunjukkan di mana elemen-elemen tersebut sama (True) atau tidak sama (False).

Contoh outputnya mungkin akan menunjukkan nilai tensor A, nilai tensor B, dan hasil perbandingan:
Tensor A:
tensor([[0.1234, 0.5678, 0.9101, 0.2345],
        [0.6789, 0.4567, 0.7890, 0.1234],
        [0.5678, 0.2345, 0.6789, 0.9012]])

Tensor B:
tensor([[0.9876, 0.5432, 0.1098, 0.7654],
        [0.1234, 0.5678, 0.9101, 0.2345],
        [0.6789, 0.4567, 0.7890, 0.1234]])

Does Tensor A equal Tensor B? (anywhere)
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
Hasilnya menunjukkan bahwa tidak ada elemen yang sama di antara random_tensor_A dan random_tensor_B, karena hasil perbandingannya adalah False di semua lokasi.

Just as you might've expected, the tensors come out with different values.

But what if you wanted to created two random tensors with the *same* values.

As in, the tensors would still contain random values but they would be of the same flavour.

That's where [`torch.manual_seed(seed)`](https://pytorch.org/docs/stable/generated/torch.manual_seed.html) comes in, where `seed` is an integer (like `42` but it could be anything) that flavours the randomness.

Let's try it out by creating some more *flavoured* random tensors.

In [71]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

Kode di atas menggunakan PyTorch untuk membuat dua tensor acak (random_tensor_C dan random_tensor_D) dengan menset seed dari generator angka acak untuk membuat hasil yang dapat direproduksi. Berikut adalah penjelasan singkat:

import torch: Baris ini mengimpor library PyTorch, memungkinkan penggunaan fungsi-fungsi dan struktur data PyTorch.

import random: Baris ini mengimpor library random, yang akan digunakan untuk mengatur seed dari generator angka acak.

RANDOM_SEED = 42: Baris ini mengatur nilai seed yang akan digunakan untuk generator angka acak.

torch.manual_seed(seed=RANDOM_SEED): Baris ini mengatur seed untuk generator angka acak PyTorch menggunakan fungsi torch.manual_seed(). Ini memastikan bahwa hasil dari fungsi-fungsi acak PyTorch akan selalu sama jika seed-nya tetap.

random_tensor_C = torch.rand(3, 4): Baris ini membuat tensor acak random_tensor_C dengan bentuk (shape) 3x4 menggunakan fungsi torch.rand().

torch.random.manual_seed(seed=RANDOM_SEED): Baris ini mengatur seed untuk generator angka acak PyTorch yang digunakan oleh fungsi-fungsi acak lainnya.

random_tensor_D = torch.rand(3, 4): Baris ini membuat tensor acak random_tensor_D dengan bentuk (shape) yang sama seperti random_tensor_C. Karena seed-nya diset ulang, tensor ini akan memiliki nilai yang sama dengan random_tensor_C.

print(f"Tensor C:\n{random_tensor_C}\n"): Baris ini mencetak atau menampilkan nilai dari tensor random_tensor_C.

print(f"Tensor D:\n{random_tensor_D}\n"): Baris ini mencetak atau menampilkan nilai dari tensor random_tensor_D.

print(f"Does Tensor C equal Tensor D? (anywhere)"): Baris ini mencetak atau menampilkan pesan pertanyaan.

random_tensor_C == random_tensor_D: Baris ini menggunakan operator perbandingan == untuk memeriksa apakah nilai-nilai elemen dalam random_tensor_C sama dengan nilai-nilai elemen dalam random_tensor_D. Hasilnya adalah tensor boolean yang menunjukkan di mana elemen-elemen tersebut sama (True) atau tidak sama (False).

Contoh outputnya mungkin akan menunjukkan nilai tensor C, nilai tensor D, dan hasil perbandingan:
Tensor C:
tensor([[0.6459, 0.4376, 0.8918, 0.9636],
        [0.3832, 0.7917, 0.6607, 0.5734],
        [0.2593, 0.8884, 0.8493, 0.7214]])

Tensor D:
tensor([[0.6459, 0.4376, 0.8918, 0.9636],
        [0.3832, 0.7917, 0.6607, 0.5734],
        [0.2593, 0.8884, 0.8493, 0.7214]])

Does Tensor C equal Tensor D? (anywhere)
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
Hasilnya menunjukkan bahwa nilai-nilai elemen dalam random_tensor_C dan random_tensor_D sama di semua lokasi, karena seed generator angka acak diset sama untuk keduanya.

Nice!

It looks like setting the seed worked.

> **Resource:** What we've just covered only scratches the surface of reproducibility in PyTorch. For more, on reproducbility in general and random seeds, I'd checkout:
> * [The PyTorch reproducibility documentation](https://pytorch.org/docs/stable/notes/randomness.html) (a good exericse would be to read through this for 10-minutes and even if you don't understand it now, being aware of it is important).
> * [The Wikipedia random seed page](https://en.wikipedia.org/wiki/Random_seed) (this'll give a good overview of random seeds and pseudorandomness in general).

## Running tensors on GPUs (and making faster computations)

Deep learning algorithms require a lot of numerical operations.

And by default these operations are often done on a CPU (computer processing unit).

However, there's another common piece of hardware called a GPU (graphics processing unit), which is often much faster at performing the specific types of operations neural networks need (matrix multiplications) than CPUs.

Your computer might have one.

If so, you should look to use it whenever you can to train neural networks because chances are it'll speed up the training time dramatically.

There are a few ways to first get access to a GPU and secondly get PyTorch to use the GPU.

> **Note:** When I reference "GPU" throughout this course, I'm referencing a [Nvidia GPU with CUDA](https://developer.nvidia.com/cuda-gpus) enabled (CUDA is a computing platform and API that helps allow GPUs be used for general purpose computing & not just graphics) unless otherwise specified.




### 1. Getting a GPU

You may already know what's going on when I say GPU. But if not, there are a few ways to get access to one.

| **Method** | **Difficulty to setup** | **Pros** | **Cons** | **How to setup** |
| ----- | ----- | ----- | ----- | ----- |
| Google Colab | Easy | Free to use, almost zero setup required, can share work with others as easy as a link | Doesn't save your data outputs, limited compute, subject to timeouts | [Follow the Google Colab Guide](https://colab.research.google.com/notebooks/gpu.ipynb) |
| Use your own | Medium | Run everything locally on your own machine | GPUs aren't free, require upfront cost | Follow the [PyTorch installation guidelines](https://pytorch.org/get-started/locally/) |
| Cloud computing (AWS, GCP, Azure) | Medium-Hard | Small upfront cost, access to almost infinite compute | Can get expensive if running continually, takes some time to setup right | Follow the [PyTorch installation guidelines](https://pytorch.org/get-started/cloud-partners/) |

There are more options for using GPUs but the above three will suffice for now.

Personally, I use a combination of Google Colab and my own personal computer for small scale experiments (and creating this course) and go to cloud resources when I need more compute power.

> **Resource:** If you're looking to purchase a GPU of your own but not sure what to get, [Tim Dettmers has an excellent guide](https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/).

To check if you've got access to a Nvidia GPU, you can run `!nvidia-smi` where the `!` (also called bang) means "run this on the command line".



In [72]:
!nvidia-smi

Sun Dec 31 12:37:43 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

Perintah !nvidia-smi digunakan untuk menampilkan informasi tentang perangkat GPU (Graphics Processing Unit) yang terpasang di sistem. Ini umumnya digunakan di lingkungan pengembangan atau komputasi yang menggunakan GPU, seperti ketika Anda menjalankan kode PyTorch atau TensorFlow yang memanfaatkan akselerasi GPU.

Berikut adalah penjelasan singkat:

!: Tanda seru (!) digunakan di beberapa lingkungan pengembangan (seperti Jupyter Notebook atau Google Colab) untuk menjalankan perintah shell atau sistem operasi.

nvidia-smi: Ini adalah perintah sistem operasi untuk menampilkan informasi tentang GPU NVIDIA yang terpasang pada sistem. Informasi ini mencakup detail seperti nama GPU, penggunaan GPU saat ini, suhu, penggunaan memori, dan lainnya.

Ketika Anda menjalankan !nvidia-smi, outputnya akan menampilkan tabel yang memberikan gambaran tentang status dan utilitas GPU yang ada di sistem pada saat itu. Informasi ini dapat sangat berguna untuk memantau penggunaan GPU, memastikan bahwa model dan pelatihan Anda berjalan pada perangkat keras yang diinginkan, serta memantau sumber daya yang digunakan.

If you don't have a Nvidia GPU accessible, the above will output something like:

```
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

In that case, go back up and follow the install steps.

If you do have a GPU, the line above will output something like:

```
Wed Jan 19 22:09:08 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.46       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```



### 2. Getting PyTorch to run on the GPU

Once you've got a GPU ready to access, the next step is getting PyTorch to use for storing data (tensors) and computing on data (performing operations on tensors).

To do so, you can use the [`torch.cuda`](https://pytorch.org/docs/stable/cuda.html) package.

Rather than talk about it, let's try it out.

You can test if PyTorch has access to a GPU using [`torch.cuda.is_available()`](https://pytorch.org/docs/stable/generated/torch.cuda.is_available.html#torch.cuda.is_available).


In [73]:
# Check for GPU
import torch
torch.cuda.is_available()

True

Kode di atas menggunakan PyTorch untuk memeriksa apakah sistem memiliki GPU yang tersedia atau tidak. Berikut adalah penjelasan singkat:

import torch: Baris ini mengimpor library PyTorch, memungkinkan penggunaan fungsi-fungsi dan struktur data PyTorch.

torch.cuda.is_available(): Baris ini memanggil fungsi is_available() dari modul cuda di PyTorch. Fungsi ini mengembalikan nilai boolean (True atau False) yang menunjukkan apakah GPU tersedia atau tidak di sistem saat ini.

Jika nilai yang dikembalikan adalah True, itu berarti GPU tersedia dan dapat digunakan untuk akselerasi perhitungan PyTorch. Jika nilai yang dikembalikan adalah False, itu berarti sistem tidak memiliki GPU yang tersedia, dan PyTorch akan menggunakan CPU untuk perhitungan.

If the above outputs `True`, PyTorch can see and use the GPU, if it outputs `False`, it can't see the GPU and in that case, you'll have to go back through the installation steps.

Now, let's say you wanted to setup your code so it ran on CPU *or* the GPU if it was available.

That way, if you or someone decides to run your code, it'll work regardless of the computing device they're using.

Let's create a `device` variable to store what kind of device is available.

In [74]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

Kode di atas mengatur tipe perangkat (device type) yang akan digunakan dalam komputasi PyTorch, berdasarkan ketersediaan GPU di sistem. Berikut adalah penjelasan singkat:

device = "cuda" if torch.cuda.is_available() else "cpu": Baris ini menggunakan ekspresi bersyarat (conditional expression) untuk menetapkan nilai ke variabel device. Jika torch.cuda.is_available() mengembalikan True (artinya GPU tersedia), maka device diatur ke string "cuda". Jika GPU tidak tersedia, maka device diatur ke string "cpu".

device: Variabel ini akan berisi tipe perangkat yang akan digunakan dalam komputasi PyTorch, yaitu "cuda" jika GPU tersedia, dan "cpu" jika tidak.

Penggunaan tipe perangkat ini dapat berguna saat membuat tensor atau model PyTorch untuk menentukan apakah perhitungan akan dilakukan pada CPU atau GPU. Misalnya, ketika membuat tensor, Anda dapat menggunakan argumen device=device untuk menetapkan perangkat yang akan digunakan.

If the above output `"cuda"` it means we can set all of our PyTorch code to use the available CUDA device (a GPU) and if it output `"cpu"`, our PyTorch code will stick with the CPU.

> **Note:** In PyTorch, it's best practice to write [**device agnostic code**](https://pytorch.org/docs/master/notes/cuda.html#device-agnostic-code). This means code that'll run on CPU (always available) or GPU (if available).

If you want to do faster computing you can use a GPU but if you want to do *much* faster computing, you can use multiple GPUs.

You can count the number of GPUs PyTorch has access to using [`torch.cuda.device_count()`](https://pytorch.org/docs/stable/generated/torch.cuda.device_count.html#torch.cuda.device_count).

In [75]:
# Count number of devices
torch.cuda.device_count()

1


Kode di atas menggunakan PyTorch untuk menghitung jumlah perangkat GPU (Graphics Processing Unit) yang tersedia di sistem. Berikut adalah penjelasan singkat:

torch.cuda.device_count(): Baris ini memanggil fungsi device_count() dari modul cuda di PyTorch. Fungsi ini mengembalikan jumlah perangkat GPU yang terdeteksi di sistem.

Hasilnya adalah bilangan bulat yang menunjukkan jumlah perangkat GPU yang tersedia. Jika hasilnya adalah 0, itu berarti tidak ada GPU yang terdeteksi, dan PyTorch akan menggunakan CPU secara default. Jika hasilnya lebih besar dari 0, itu menunjukkan jumlah GPU yang tersedia.

Knowing the number of GPUs PyTorch has access to is helpful incase you wanted to run a specific process on one GPU and another process on another (PyTorch also has features to let you run a process across *all* GPUs).

### 3. Putting tensors (and models) on the GPU

You can put tensors (and models, we'll see this later) on a specific device by calling [`to(device)`](https://pytorch.org/docs/stable/generated/torch.Tensor.to.html) on them. Where `device` is the target device you'd like the tensor (or model) to go to.

Why do this?

GPUs offer far faster numerical computing than CPUs do and if a GPU isn't available, because of our **device agnostic code** (see above), it'll run on the CPU.

> **Note:** Putting a tensor on GPU using `to(device)` (e.g. `some_tensor.to(device)`) returns a copy of that tensor, e.g. the same tensor will be on CPU and GPU. To overwrite tensors, reassign them:
>
> `some_tensor = some_tensor.to(device)`

Let's try creating a tensor and putting it on the GPU (if it's available).

In [76]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

Kode di atas mengilustrasikan cara membuat tensor di PyTorch, menunjukkan perangkat di mana tensor berada, dan bagaimana memindahkan tensor ke GPU jika GPU tersedia. Berikut adalah penjelasan singkat:

tensor = torch.tensor([1, 2, 3]): Baris ini membuat tensor PyTorch dengan nilai [1, 2, 3]. Secara default, tensor akan dibuat di CPU jika tidak ada instruksi khusus untuk menetapkannya ke perangkat lain.

print(tensor, tensor.device): Baris ini mencetak atau menampilkan nilai dari tensor dan perangkat tempat tensor tersebut berada. tensor.device memberikan informasi tentang perangkat tempat tensor tersebut disimpan, dan karena tidak ada spesifikasi, tensor akan berada di CPU.

tensor_on_gpu = tensor.to(device): Baris ini menggunakan metode .to() untuk memindahkan tensor ke perangkat yang ditentukan. Variabel device sebelumnya diberikan nilai "cuda" jika GPU tersedia, atau "cpu" jika tidak. Sebagai contoh, jika GPU tersedia, tensor_on_gpu akan menjadi salinan tensor yang berada di GPU.

tensor_on_gpu: Hasilnya adalah tensor yang telah dipindahkan ke perangkat yang ditentukan.

If you have a GPU available, the above code will output something like:

```
tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0')
```

Notice the second tensor has `device='cuda:0'`, this means it's stored on the 0th GPU available (GPUs are 0 indexed, if two GPUs were available, they'd be `'cuda:0'` and `'cuda:1'` respectively, up to `'cuda:n'`).



### 4. Moving tensors back to the CPU

What if we wanted to move the tensor back to CPU?

For example, you'll want to do this if you want to interact with your tensors with NumPy (NumPy does not leverage the GPU).

Let's try using the [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) method on our `tensor_on_gpu`.

In [79]:
# Contoh tensor di GPU
tensor_on_gpu = torch.tensor([1, 2, 3], device='cuda:0')

# Memindahkan tensor dari GPU ke CPU
tensor_on_cpu = tensor_on_gpu.cpu()

# Mengonversi tensor yang berada di CPU menjadi NumPy array
numpy_array = tensor_on_cpu.numpy()

print(numpy_array)

[1 2 3]


# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()
saat kode akan dirun terjadi error, Error tersebut terjadi karena Anda mencoba mengonversi tensor yang berada di GPU (cuda:0) langsung menjadi NumPy array. Untuk memperbaiki ini, Anda perlu memindahkan tensor dari GPU ke CPU terlebih dahulu, dan baru kemudian mengonversikannya menjadi NumPy array. Dalam contoh di atas, cpu() digunakan untuk memindahkan tensor dari GPU ke CPU, dan setelah itu, Anda dapat menggunakan numpy() untuk mengonversikannya menjadi NumPy array.


Kode di atas mengilustrasikan contoh penggunaan PyTorch untuk bekerja dengan tensor di GPU, memindahkan tensor dari GPU ke CPU, dan mengonversi tensor ke NumPy array. Berikut adalah penjelasan singkat:

tensor_on_gpu = torch.tensor([1, 2, 3], device='cuda:0'): Baris ini membuat tensor PyTorch dengan nilai [1, 2, 3] dan menetapkannya ke GPU dengan menyertakan argumen device='cuda:0'. Angka 0 dalam 'cuda:0' merujuk pada nomor identifikasi GPU jika ada lebih dari satu GPU.

tensor_on_cpu = tensor_on_gpu.cpu(): Baris ini menggunakan metode .cpu() untuk memindahkan tensor dari GPU ke CPU. Ini berguna jika Anda ingin melanjutkan komputasi di CPU setelah selesai melakukan operasi di GPU.

numpy_array = tensor_on_cpu.numpy(): Baris ini menggunakan metode .numpy() untuk mengonversi tensor PyTorch yang berada di CPU menjadi NumPy array. NumPy array dapat digunakan dengan berbagai library dan fungsi-fungsi yang mendukung NumPy.

print(numpy_array): Baris ini mencetak atau menampilkan nilai dari NumPy array yang dihasilkan.

Instead, to get a tensor back to CPU and usable with NumPy we can use [`Tensor.cpu()`](https://pytorch.org/docs/stable/generated/torch.Tensor.cpu.html).

This copies the tensor to CPU memory so it's usable with CPUs.

In [78]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

Kode di atas menunjukkan cara lain untuk mengonversi tensor yang berada di GPU ke NumPy array, tetapi kali ini menggunakan pendekatan yang lebih ringkas dengan menggabungkan pemindahan tensor ke CPU dan konversi ke NumPy array dalam satu baris. Berikut adalah penjelasan singkat:

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy(): Baris ini menggunakan metode .cpu() untuk memindahkan tensor dari GPU ke CPU, kemudian langsung menggunakan metode .numpy() untuk mengonversi tensor tersebut ke NumPy array.

tensor_back_on_cpu: Hasilnya adalah NumPy array yang dihasilkan.

The above returns a copy of the GPU tensor in CPU memory so the original tensor is still on GPU.

In [80]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

tensor_on_gpu adalah sebuah tensor PyTorch yang dibuat dan disimpan di GPU (Graphics Processing Unit). Berikut adalah penjelasan singkat:

tensor_on_gpu: Variabel ini adalah tensor PyTorch yang menyimpan nilai [1, 2, 3] dan ditempatkan di GPU. Hal ini dicapai dengan menyertakan argumen device='cuda:0' saat membuat tensor. cuda:0 merujuk pada GPU pertama yang terdeteksi di sistem.
tensor_on_gpu digunakan untuk menunjukkan bagaimana membuat tensor di GPU dan kemudian melakukan operasi pada CPU atau mengonversinya ke NumPy array jika diperlukan. Variabel semacam ini penting dalam pengembangan dengan PyTorch, terutama ketika bekerja dengan perangkat keras akselerasi seperti GPU untuk meningkatkan kecepatan perhitungan.

## Exercises

All of the exercises are focused on practicing the code above.

You should be able to complete them by referencing each section or by following the resource(s) linked.

**Resources:**

* [Exercise template notebook for 00](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb).
* [Example solutions notebook for 00](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/solutions/00_pytorch_fundamentals_exercise_solutions.ipynb) (try the exercises *before* looking at this).

1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor) and for [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).
2. Create a random tensor with shape `(7, 7)`.
3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).
4. Set the random seed to `0` and do exercises 2 & 3 over again.
5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one). If there is, set the GPU random seed to `1234`.
6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed).
7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
8. Find the maximum and minimum values of the output of 7.
9. Find the maximum and minimum index values of the output of 7.
10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

## Extra-curriculum

* Spend 1-hour going through the [PyTorch basics tutorial](https://pytorch.org/tutorials/beginner/basics/intro.html) (I'd recommend the [Quickstart](https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html) and [Tensors](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html) sections).
* To learn more on how a tensor can represent data, see this video: [What's a tensor?](https://youtu.be/f5liqUk0ZTw)